# Execute with
# ansible-playbook windmill_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create and start windmill service
  hosts: my_servers
  vars:
    USERNAME: '{{ secrets.WINDMILL.USERNAME }}'
  tasks:
  - name: Stop windmill service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Stop windmill_server container
    community.docker.docker_container:
      name: windmill_server
      state: stopped
      image: ghcr.io/windmill-labs/windmill:main

  - name: Remove windmill_server container
    community.docker.docker_container:
      name: windmill_server
      state: absent
      image: ghcr.io/windmill-labs/windmill:main

  - name: Remove windmill image
    community.docker.docker_image:
      name: ghcr.io/windmill-labs/windmill
      tag: latest
      state: absent

  - name: Start windmill service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      daemon_reload: true
      enabled: true
