---
networks:
  pangolin_newt:
    external: true
services:
  pinchflat:
    container_name: pinchflat
    restart: unless-stopped
    image: ghcr.io/kieraneglin/pinchflat:latest
    user: 0:{{ SYNCTHING_GROUP_ID.stdout }}
    volumes:
      - ./config:/config
      - /home/syncthing/data1/media-pinchflat:/downloads
    environment:
      - YT_DLP_WORKER_CONCURRENCY=1
      - LOG_LEVEL=info
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.pinchflat.name=Pinchflat
      - pangolin.public-resources.pinchflat.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.pinchflat.protocol=http
      - pangolin.public-resources.pinchflat.auth.sso-enabled=true
      - pangolin.public-resources.pinchflat.targets[0].method=http
      - pangolin.public-resources.pinchflat.targets[0].port={{ APPLICATION_PORT }}
