networks:
  '{{secrets.TRAFIK_NETWORK}}':
    external: true

# Open postgresql console to enter queries
# docker exec -it postgres_postgres psql -U postgres -d postgres


# Dump from docker container:
# docker exec postgres_postgres pg_dump -U postgres -d postgres -F c --compress=zstd:9 > temp_zstd_9.dump

# Restore to docker container:
# cat temp_zstd_9.dump | docker exec -i postgres_postgres pg_restore -U postgres -d postgres


# Remote dump:
# pg_dump CONNECTION_STRING -U postgres > dump.sql

# Remote restore specific table:
# pg_restore -d CONNECTION_STRING -U postgres -t TABLE_NAME dump.sql

# Or:
# psql CONNECTION_STRING -f dump.sql -F t


# Copy table(s) from one database to another on same postgres instance
# docker exec -i postgres_postgres \
#    bash -c "pg_dump -U postgres -t <table_name> <old_database_name> | psql -U postgres <new_database_name>"


# Upgrade postgres:
#   Dump db data to file
#     docker compose exec postgres pg_dumpall -U postgres > dump.sql

#   Shut down db
#     docker compose down
#   Delete postgres folder
#     mv postgres_data postgres_data_bak

#   Update postgres major version in docker compose file
#     docker compose up -d
#     cp dump.sql postgres_data/dump.sql
#   Restore data
#     docker compose exec postgres bash
#     psql -U postgres -f dump.sql

services:
  postgres:
    container_name: postgres_postgres
    # In pgadmin and nocodb we can now use connection string where hostname is 'postgres_postgres'
    # postgres://user:password@host/dbname
    # nocodb:
    # postgresql://{ POSTGRES_USER }:{ POSTGRES_PASSWORD }@postgres_postgres:5432/{ POSTGRES_DATABASE }
    hostname: postgres_postgres
    image: postgres:16-alpine
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: '{{ secrets.POSTGRES.POSTGRES_USER }}'
      POSTGRES_PASSWORD: '{{ secrets.POSTGRES.POSTGRES_PASSWORD }}'
    volumes:
    - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    # TODO Add default connection if possible
    container_name: postgres_pgadmin
    image: dpage/pgadmin4:8
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    labels:
    - traefik.enable=true
    - traefik.http.routers.{{ secrets.POSTGRES.PGADMIN_USERNAME }}.rule=Host(`{{ secrets.POSTGRES.PGADMIN_USERNAME }}.{{ secrets.MY_DOMAIN }}`)
    - traefik.http.services.{{ secrets.POSTGRES.PGADMIN_USERNAME }}.loadbalancer.server.port={{ APPLICATION_PORT }}
    - traefik.http.routers.{{ secrets.POSTGRES.PGADMIN_USERNAME }}.tls=true
    - traefik.http.routers.{{ secrets.POSTGRES.PGADMIN_USERNAME }}.tls.certresolver=production
    - traefik.http.routers.{{ secrets.POSTGRES.PGADMIN_USERNAME }}.middlewares=authelia@docker
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: '{{ secrets.POSTGRES.PGADMIN_USER }}'
      PGADMIN_DEFAULT_PASSWORD: '{{ secrets.POSTGRES.PGADMIN_PASSWORD }}'
    volumes:
    # pgadmindata folder needs to be owned by user id '5050'
    - ./pgadmindata:/var/lib/pgadmin

  nocodb:
    # TODO Add default connection if possible
    container_name: postgres_nocodb
    image: nocodb/nocodb:latest
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    labels:
    - traefik.enable=true
    - traefik.http.routers.{{ secrets.POSTGRES.NOCODB_USERNAME }}.rule=Host(`{{ secrets.POSTGRES.NOCODB_USERNAME }}.{{ secrets.MY_DOMAIN }}`)
    - traefik.http.services.{{ secrets.POSTGRES.NOCODB_USERNAME }}.loadbalancer.server.port={{ APPLICATION2_PORT }}
    - traefik.http.routers.{{ secrets.POSTGRES.NOCODB_USERNAME }}.tls=true
    - traefik.http.routers.{{ secrets.POSTGRES.NOCODB_USERNAME }}.tls.certresolver=production
    - traefik.http.routers.{{ secrets.POSTGRES.NOCODB_USERNAME }}.middlewares=authelia@docker
    restart: unless-stopped
    volumes:
    - ./nocodb:/usr/app/data/
