# https://github.com/nocodb/nocodb 
# https://www.nocodb.com/ 
# Execute with
# ansible-playbook postgres_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.POSTGRES.USERNAME }}"
    SUBDOMAIN: "{{ secrets.POSTGRES.PGADMIN_USERNAME }}"
    APPLICATION_PORT: "80"
    APPLICATION2_PORT: "8080"
    BACKUP_PASSWORD: "{{ secrets.RDIFF_BACKUP.BACKUP_PASSWORD }}"
  tasks:
  - name: Create group
    ansible.builtin.group:
      name: '{{ USERNAME }}'
      state: present

  - name: Create user
    ansible.builtin.user:
      name: '{{ USERNAME }}'
      groups:
      - '{{ USERNAME }}'
      - docker
      shell: '{{ secrets.DEFAULT_SHELL }}'

  - name: Get syncthing user id
    ansible.builtin.shell:
      cmd: id syncthing -u
    register: SYNCTHING_USER_ID

  - name: Get syncthing group id
    ansible.builtin.shell:
      cmd: id syncthing -g
    register: SYNCTHING_GROUP_ID

  - name: Create directories
    file:
      path: /home/{{ USERNAME }}/pgadmindata
      recurse: true
      state: directory
      # pgadmin user
      owner: '5050'
      group: '5050'
      
  - name: Copy docker-compose.yml file
    template:
      src: docker-compose.yml
      dest: /home/{{ USERNAME }}/docker-compose.yml

  - name: Run `docker-compose up` again
    community.docker.docker_compose_v2:
      project_src: /home/{{ USERNAME }}
      pull: always

  - name: Create directories
    file:
      path: '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}' 
      recurse: true
      state: directory
      owner: '{{ SYNCTHING_USER_ID.stdout }}'
      group: '{{ SYNCTHING_GROUP_ID.stdout }}'

  - name: Copy backup script file
    template:
      src: backup_postgres.sh
      dest: '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres.sh'
      # owner: '{{ USER_ID.stdout }}'
      # group: '{{ GROUP_ID.stdout }}'

  - name: Create cron job for database 'postgres'
    ansible.builtin.cron:
      name: Run postgres backup database 'postgres'
      job: /bin/bash '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres.sh' postgres '{{ BACKUP_PASSWORD }}' >> '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres_postgres.log'
      minute: "0"
      hour: "3"
      user: root

  - name: Create cron job for database 'stream_announcer'
    ansible.builtin.cron:
      name: Run postgres backup database 'stream_announcer'
      job: /bin/bash '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres.sh' stream_announcer '{{ BACKUP_PASSWORD }}' >> '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres_stream_announcer.log'
      minute: "0"
      hour: "3"
      user: root

  - name: Create cron job for database 'ladder_announcer'
    ansible.builtin.cron:
      name: Run postgres backup database 'ladder_announcer'
      job: /bin/bash '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres.sh' ladder_announcer '{{ BACKUP_PASSWORD }}' >> '{{ secrets.POSTGRES.BACKUP_MOUNT_PATH }}/backup_postgres_ladder_announcer.log'
      minute: "0"
      hour: "3"
      user: root
