# https://github.com/rdiff-backup/rdiff-backup
# Execute with
# ansible-playbook rdiff_backup_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create and start duplicati service
  hosts: my_servers
  vars:
    USERNAME: root
    BACKUP_SCRIPT_PATH: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/backup_script.sh"
    AMOUNT_OF_BACKUPS: 3
    BACKUP_PASSWORD: "{{ secrets.RDIFF_BACKUP.BACKUP_PASSWORD }}"
    backup_jobs:
      - name: audiobookshelf
        LOG_NAME: backup_audiobookshelf.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_AUDIOBOOKSHELF }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/audiobookshelf"
      - name: bookshelf
        LOG_NAME: backup_bookshelf.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_BOOKSTACK }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/bookstack"
      - name: changedetection
        LOG_NAME: backup_changedetection.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_CHANGEDETECTION }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/changedetection"
      - name: factorio
        LOG_NAME: backup_factorio.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_FACTORIO }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/factorio"
      - name: jellyfin
        LOG_NAME: backup_jellyfin.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_JELLYFIN }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/jellyfin"
      - name: navidrome
        LOG_NAME: backup_navidrome.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_NAVIDROME }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/navidrome"
      - name: uptime_kuma
        LOG_NAME: backup_uptime_kuma.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_UPTIME_KUMA }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/uptime_kuma"
      - name: paperless
        LOG_NAME: backup_paperless.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_PAPERLESS }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/paperless"
      - name: owncloud
        LOG_NAME: backup_owncloud.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_OWNCLOUD }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/owncloud"
      - name: reactive_resume
        LOG_NAME: backup_reactive_resume.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_REACTIVE_RESUME }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/reactive_resume"
      - name: trillium
        LOG_NAME: backup_trillium.log
        SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_TRILLIUM }}"
        TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/trillium"
      # - name: uptime_kuma
      #   LOG_NAME: backup_uptime_kuma.log
      #   SOURCE_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_SOURCE_UPTIME_KUMA }}"
      #   TARGET_DIRECTORY: "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/uptime_kuma"
  tasks:
    - name: Get syncthing user id
      ansible.builtin.shell:
        cmd: id syncthing -u
      register: SYNCTHING_USER_ID

    - name: Get syncthing group id
      ansible.builtin.shell:
        cmd: id syncthing -g
      register: SYNCTHING_GROUP_ID

    - name: Create directories
      file:
        path: "{{ item }}"
        recurse: true
        state: directory
        owner: "{{ SYNCTHING_USER_ID.stdout }}"
        group: "{{ SYNCTHING_GROUP_ID.stdout }}"
      loop:
        - "{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}"

    - name: Copy backup script
      template:
        src: backup_script.sh
        dest: "{{ BACKUP_SCRIPT_PATH }}"
        owner: "{{ SYNCTHING_USER_ID.stdout }}"
        group: "{{ SYNCTHING_GROUP_ID.stdout }}"

    - name: Add backups
      ansible.builtin.cron:
        name: "Run {{ item.name }} backup"
        job: /bin/bash '{{ BACKUP_SCRIPT_PATH }}' '{{ item.SOURCE_DIRECTORY }}' '{{ item.TARGET_DIRECTORY }}' '{{ AMOUNT_OF_BACKUPS }}' '{{ BACKUP_PASSWORD }}' >> '{{ secrets.RDIFF_BACKUP.BACKUP_TARGET_PATH }}/{{ item.LOG_NAME }}'
        minute: "0"
        hour: "4"
        user: "{{ USERNAME }}"
      with_items: "{{ backup_jobs }}"
