VERSION 0.6
# earthly +all --PYTHONVERSION=3.12
ARG PYTHONVERSION=3.11
FROM ghcr.io/astral-sh/uv:python${PYTHONVERSION}-bookworm-slim
WORKDIR /root/transcriber_backend

install-dev:
    # RUN apt update && apt install -y gcc # Required by tgcrypto
    COPY uv.lock pyproject.toml ./
    RUN uv sync --frozen --no-cache --no-install-project
    COPY src src

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install uv
    # uv sync

    # Convert single to double quotes
    RUN uv run ruff check . --select Q --fix
    # Remove unused imports
    RUN uv run ruff check . --select F --fix
    # Sort imports
    RUN uv run ruff check . --select I --fix
    # Format code
    RUN uv run ruff format .

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN uv run ruff format . --check --diff

# Ignore errors via "# noqa: F841"
lint:
    FROM +install-dev
    RUN uv run ruff check .

# Ignore errors via "# pyrefly: ignore"
pyrefly:
    FROM +install-dev
    RUN uv run pyrefly check

pytest:
    FROM +install-dev
    # TODO fix me
    # RUN uv run python -m pytest test

pre-commit:
    BUILD +format-check
    BUILD +lint
    BUILD +pyrefly

all:
    BUILD +pre-commit
    BUILD +pytest
