VERSION 0.6
# earthly +all --PYTHONVERSION=3.11 --NODEVERSION=19
ARG PYTHONVERSION=3.11
ARG NODEVERSION=19 # 14, 16, 18, 19
FROM python:${PYTHONVERSION}-slim
WORKDIR /root/transcriber_backend

install-dev:
    RUN pip install poetry --no-cache-dir
    COPY poetry.lock pyproject.toml ./
    RUN poetry install
    COPY . /root/transcriber_backend
    RUN touch SECRETS.toml

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install poetry
    # poetry install

    # Convert single to double quotes
    RUN poetry run ruff check . --select Q --fix
    # Remove unused imports
    RUN poetry run ruff check . --select F --fix
    # Sort imports
    RUN poetry run ruff check . --select I --fix
    # Format code
    RUN poetry run ruff format .

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN poetry run ruff format . --check --diff

# Ignore errors via "# noqa: F841"
lint:
    FROM +install-dev
    RUN poetry run ruff check .

# Ignore errors via "# pyre-fixme[11]"
pyre:
    FROM +install-dev
    RUN poetry run pyre

pytest:
    FROM +install-dev
    # TODO fix me
    # RUN poetry run python -m pytest test

pre-commit:
    BUILD +format-check
    BUILD +lint
    BUILD +pyre

all:
    BUILD +pre-commit
    BUILD +pytest
