stage = "DEV"

# Database connection
postgres_provider = 'postgres'
postgres_user = 'postgres'
postgres_database = 'postgres'
postgres_password = 'your_db_pw'
postgres_host = 'your-domain.com'
postgres_port = "5432"

# Whisper settings 
models_root = "./whisper_models"

# Transcribe settings
workers_limit = 1

# File settings
finder_add_glob_pattern = "*extracted_audio/*.mp3"
finder_ignore_glob_pattern = "*/downloading/*"
finder_folders_to_parse = ["/root/path/to/your/files"]

