# Rename me to "SECRETS.toml"
[Transcriber]
stage = "DEV"

# Database connection
postgres_provider = 'postgres'
postgres_user = 'postgres'
postgres_database = 'postgres'
postgres_password = 'your_db_pw'
postgres_host = 'your-domain.com'
postgres_port = "5432"

# Transcribe settings
workers_limit = 1
workers_acceptable_models = ["Tiny", "Base", "Small"]
detect_language_before_queueing = true
detect_language_before_queueing_min_size_bytes = 10_000_000

# File settings
finder_add_glob_pattern = "*extracted_audio/*.mp3"
finder_ignore_glob_pattern = "*/downloading/*"
finder_folders_to_parse = ["/root/path/to/your/files"]



[TelegramDownloader]
api_id = 123456789
api_hash = "your_api_hash"
stage = "DEV"

# Which channels to download from
channel_ids = ["channel_name"]
# Which types to download
media_types = ["audio", "photo", "video"]
# Store video files or convert them to mp3
extract_audio_from_videos = true
# Download folder
output_folder = "/your/download/folder"
# Parallel downloads
parallel_downloads_count = 5

# Filters
media_min_date = 1000-01-01T00:00:00
media_max_date = 9999-01-01T00:00:00
# Photo
photo_min_file_size_bytes = 0
photo_max_file_size_bytes = 4_000_000_000
photo_min_width = 0
photo_max_width = 1_000_000
photo_min_height = 0
photo_max_height = 1_000_000
# Video
video_min_file_size_bytes = 0
video_max_file_size_bytes = 4_000_000_000
video_min_file_duration_seconds = 0
video_max_file_duration_seconds = 4_000_000_000
video_min_width = 0
video_max_width = 1_000_000
video_min_height = 0
video_max_height = 1_000_000
# Audio
audio_min_file_size_bytes = 0
audio_max_file_size_bytes = 4_000_000_000
audio_min_file_duration_seconds = 0
audio_max_file_duration_seconds = 4_000_000_000

[TextSearcher]
glob_pattern = "%my_test_regex%" # Doesnt work
regex_pattern = ".*my_test_regex.*"
allowed_languages = ["de", "en"]
