---
# https://docs.mealie.io
networks:
  pangolin_newt:
    external: true
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    volumes:
      - ./mealie-data:/app/data/
    networks:
      - pangolin_newt
    environment:
      ALLOW_SIGNUP: 'false'
      LOG_LEVEL: DEBUG
      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
    labels:
      - pangolin.public-resources.mealie.name=Mealie
      - pangolin.public-resources.mealie.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.mealie.protocol=http
      - pangolin.public-resources.mealie.auth.sso-enabled=false
      - pangolin.public-resources.mealie.targets[0].method=http
      - pangolin.public-resources.mealie.targets[0].port={{ APPLICATION_PORT }}
