# Stop factorio service, remove container, remove image, start service
# Execute with
# ansible-playbook factorio_update.yml -i ../hosts
- name: Update factorio
  hosts: my_servers
  vars:
    USERNAME: factorio
  tasks:
  - name: Stop factorio service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Stop factorio container
    community.docker.docker_container:
      name: '{{ USERNAME }}'
      state: stopped
      image: factoriotools/factorio

  - name: Remove factorio container
    community.docker.docker_container:
      name: '{{ USERNAME }}'
      state: absent
      image: factoriotools/factorio

  - name: Remove factorio image
    community.docker.docker_image:
      name: factoriotools/factorio
      tag: latest
      state: absent

  - name: Start factorio service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      enabled: true

