---
networks:
  pangolin_newt:
    external: true
services:
  navidrome:
    container_name: navidrome
    hostname: navidrome
    image: deluan/navidrome
    restart: unless-stopped
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.navidrome.name=Navidrome
      - pangolin.public-resources.navidrome.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.navidrome.protocol=http
      - pangolin.public-resources.navidrome.auth.sso-enabled=false
      - pangolin.public-resources.navidrome.targets[0].method=http
      - pangolin.public-resources.navidrome.targets[0].port={{ APPLICATION_PORT }}
    volumes:
      - /home/{{ USERNAME }}/data:/data
      - '{{ secrets.NAVIDROME.MEDIA_FOLDER }}:/music:ro'
