---
networks:
  pangolin_newt:
    external: true
services:
  uptime-kuma:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    networks:
      - pangolin_newt
    labels:
      # WHY sso-disabled: was authelia@docker, now pangolin sso-enabled=false
      - pangolin.public-resources.uptime-kuma.name=Uptime Kuma
      - pangolin.public-resources.uptime-kuma.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_PUBLIC_DOMAIN }}
      - pangolin.public-resources.uptime-kuma.protocol=http
      - pangolin.public-resources.uptime-kuma.auth.sso-enabled=false
      - pangolin.public-resources.uptime-kuma.targets[0].site=local
      - pangolin.public-resources.uptime-kuma.targets[0].method=http
      - pangolin.public-resources.uptime-kuma.targets[0].hostname=uptime-kuma
      - pangolin.public-resources.uptime-kuma.targets[0].port={{ APPLICATION_PORT }}
    volumes:
      - ./uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
