# Execute with
# ansible-playbook uptime_kuma_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create and start uptime_kuma service
  hosts: all
  vars:
    USERNAME: '{{ secrets.UPTIME_KUMA.USERNAME }}'
  tasks:

  - name: Create systemd file
    template:
      src: uptime_kuma.service
      dest: /etc/systemd/system/{{ USERNAME }}.service
      owner: '{{ USER_ID.stdout }}'
      group: '{{ GROUP_ID.stdout }}'

  - name: Stop uptime_kuma service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Remove uptime_kuma container
    community.docker.docker_container:
      name: uptime-kuma
      state: absent
      image: louislam/uptime-kuma:1 

  - name: Remove uptime_kuma image
    community.docker.docker_image:
      name: louislam/uptime-kuma
      tag: 1
      state: absent

  - name: Start uptime_kuma service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      daemon_reload: true
      enabled: true
