# https://github.com/louislam/uptime-kuma
# Execute with
# ansible-playbook uptime_kuma_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.UPTIME_KUMA.USERNAME }}"
    APPLICATION_PORT: 3001
  tasks:
  - name: Create group
    ansible.builtin.group:
      name: '{{ USERNAME }}'
      state: present

  - name: Create user
    ansible.builtin.user:
      name: '{{ USERNAME }}'
      groups:
      - '{{ USERNAME }}'
      - docker
      shell: '{{ secrets.DEFAULT_SHELL }}'

  - name: Copy docker-compose.yml file
    template:
      src: docker-compose.yml
      dest: /home/{{ USERNAME }}/docker-compose.yml
      
  - name: Run `docker-compose up` again
    community.docker.docker_compose_v2:
      project_src: /home/{{ USERNAME }}
      pull: always
