# https://github.com/Didstopia/vrising-server
services:
  vrising:
    image: didstopia/vrising-server:latest
    # build: .
    container_name: vrising
    restart: unless-stopped
    environment:
      # Configure the server
      V_RISING_SERVER_PERSISTENT_DATA_PATH: "/app/vrising"
      V_RISING_SERVER_BRANCH: "public"
      # V_RISING_SERVER_START_MODE: "0" # Install/update and start server
      # V_RISING_SERVER_START_MODE: "1" # Install/update and exit
      V_RISING_SERVER_START_MODE: "2" # Install, skip update check and start server
      V_RISING_SERVER_UPDATE_MODE: "1" # Enable update checking
      V_RISING_SERVER_DEFAULT_HOST_SETTINGS: false
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
      - "9878:9878/tcp"
    volumes:
      - ./vrising_saves:/app/vrising
      - ./vrising_data:/steamcmd/vrising
    deploy:
      resources:
        limits:
          # cpus: '0.5'
          memory: 6000M