# https://github.com/Didstopia/vrising-server
version: '3.8'

networks:
  '{{secrets.TRAFIK_NETWORK}}':
    external: true

services:
  vrising:
    image: didstopia/vrising-server:latest
    # build: .
    container_name: vrising
    # restart: unless-stopped
    restart: no
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    environment:
      # Configure the server
      V_RISING_SERVER_PERSISTENT_DATA_PATH: "/app/vrising"
      V_RISING_SERVER_BRANCH: "public"
      # V_RISING_SERVER_START_MODE: "0" # Install/update and start server
      # V_RISING_SERVER_START_MODE: "1" # Install/update and exit
      V_RISING_SERVER_START_MODE: "2" # Install, skip update check and start server
      V_RISING_SERVER_UPDATE_MODE: "1" # Enable update checking

      # Customize the server
      V_RISING_SERVER_NAME: "{{ secrets.VRISING.SERVER_NAME }}"
      V_RISING_SERVER_DESCRIPTION: "Burny's server."
      V_RISING_SERVER_GAME_PORT: 9876
      V_RISING_SERVER_QUERY_PORT: 9877
      V_RISING_SERVER_RCON_PORT: 9878
      V_RISING_SERVER_RCON_ENABLED: true
      V_RISING_SERVER_RCON_PASSWORD: "rc0n"
      V_RISING_SERVER_MAX_CONNECTED_USERS: 1
      V_RISING_SERVER_MAX_CONNECTED_ADMINS: 1
      V_RISING_SERVER_SAVE_NAME: "{{ secrets.VRISING.SERVER_SAVEGAME_NAME }}"
      V_RISING_SERVER_PASSWORD: "{{ secrets.VRISING.SERVER_PASSWORD }}"
      V_RISING_SERVER_LIST_ON_MASTER_SERVER: false
      V_RISING_SERVER_LIST_ON_STEAM: false
      V_RISING_SERVER_LIST_ON_EOS: false
      V_RISING_SERVER_AUTO_SAVE_COUNT: 5
      V_RISING_SERVER_AUTO_SAVE_INTERVAL: 10
      V_RISING_SERVER_GAME_SETTINGS_PRESET: "StandardPvE"
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
      - "9878:9878/tcp"
    volumes:
      - ./vrising_saves:/app/vrising
      - ./vrising_data:/steamcmd/vrising
