# Execute with
# ansible-playbook vrising_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.VRISING.USERNAME }}"
  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{ USERNAME }}"
        state: present

    - name: Create user
      ansible.builtin.user:
        name: "{{ USERNAME }}"
        groups:
          - "{{ USERNAME }}"
          - docker
        shell: "{{ secrets.DEFAULT_SHELL }}"

    - name: Create "Settings" directory 
      ansible.builtin.file:
        path: /home/{{ USERNAME }}/vrising_saves/Settings/
        recurse: true
        state: directory
        
    - name: Copy ServerHostSettings file
      template:
        src: ServerHostSettings.json
        dest: /home/{{ USERNAME }}/vrising_saves/Settings/ServerHostSettings.json

    - name: Copy docker-compose.yml file
      template:
        src: docker-compose.yml
        dest: /home/{{ USERNAME }}/docker-compose.yml
        
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: /home/{{ USERNAME }}
        state: absent
        # Comment out to skip update
        # remove_images: all

    - name: Run `docker-compose up` again
      community.docker.docker_compose_v2:
        project_src: /home/{{ USERNAME }}
