VERSION 0.6
# earthly +all --PYTHONVERSION=3.11
ARG PYTHONVERSION=3.11
FROM python:${PYTHONVERSION}-slim
WORKDIR /root/discord_bot

# Start bot locally for development
start-dev:
    # Run on host system instead of inside a container
    LOCALLY
    RUN sh run.sh

install-dev:
    COPY poetry.lock pyproject.toml ./
    RUN pip install poetry --no-cache-dir
    RUN poetry config virtualenvs.in-project true
    # Copy cache from host system to container
    COPY --if-exists .venv ./.venv
    RUN poetry install
    SAVE ARTIFACT ./.venv
    COPY . /root/discord_bot

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install poetry
    # poetry install

    # Remove unused imports
    RUN poetry run pycln -q .
    # Sort imports
    RUN poetry run isort .
    # Format code
    RUN poetry run yapf -ir .

# Check if imports are unused
remove-unused-imports-check:
    FROM +install-dev
    RUN poetry run pycln -c .

# Check if imports require reordering
sort-imports-check:
    FROM +install-dev
    RUN poetry run isort --check-only .

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN poetry run yapf -dr .

# Ignore errors via "# Ignore F841"
lint:
    FROM +install-dev
    RUN poetry run ruff check **/*.py

# Ignore errors via "# pyre-fixme[11]"
pyre:
    FROM +install-dev
    RUN poetry run pyre

pytest:
    FROM +install-dev
    RUN poetry run pytest

export-cache:
    LOCALLY
    # Export cache from container to host system for github actions cache
    COPY +install-dev/.venv .venv

all:
    BUILD +remove-unused-imports-check
    BUILD +sort-imports-check
    BUILD +format-check
    BUILD +lint
    BUILD +pyre
    BUILD +pytest
