VERSION 0.6
FROM python:3.11-slim
WORKDIR /root/discord_bot

# Start bot locally for development
start-dev:
    FROM DOCKERFILE .
    COPY DISCORDKEY SUPABASEURL SUPABASEKEY ./
    ENV STAGE "DEV"
    RUN poetry run python main.py

install-dev:
    COPY poetry.lock pyproject.toml ./
    RUN pip install poetry --no-cache-dir \
        && poetry install
    COPY . /root/discord_bot
    # Allow imports like 'from discord_bot.commands.public_remind import Remind'
    # ENV PYTHONPATH "${PYTHONPATH}:/root"

# Check if imports are unused
remove-unused-imports-check:
    FROM +install-dev
    RUN poetry run pycln -c *.py

# Check if imports require reordering
sort-imports-check:
    FROM +install-dev
    RUN poetry run isort --check-only **/*.py

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN poetry run yapf -dr *.py

# Ignore errors via "# Ignore F841"
lint:
    FROM +install-dev
    RUN poetry run ruff check **/*.py

# Ignore errors via "# pyre-fixme[11]"
pyre:
    FROM +install-dev
    RUN poetry run pyre

pytest:
    FROM +install-dev
    RUN poetry run pytest

all:
    BUILD +remove-unused-imports-check
    BUILD +sort-imports-check
    BUILD +format-check
    BUILD +lint
    BUILD +pyre
    BUILD +pytest
