[tool.poetry]
name = "discord_bot"
version = "0.1.0"
description = ""
authors = ["burny <gamingburny@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
arrow = "^1.2.2"
hikari = "^2.0.0-alpha.108"
loguru = "^0.6.0"
ptable = "^0.9.2"

[tool.poetry.dev-dependencies]
hypothesis = "^6.8.5"
pytest = "^6.2.3"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
