VERSION 0.6
# earthly +all --PYTHONVERSION=3.12
ARG PYTHONVERSION=3.12
FROM python:${PYTHONVERSION}-slim
WORKDIR /root/python_examples

# Run local example python file
start-dev:
    # Run on host system instead of inside a container
    LOCALLY
    RUN poetry run python main.py

install-dev:
    RUN pip install poetry --no-cache-dir
    COPY poetry.lock pyproject.toml ./
    RUN poetry install
    COPY . /root/python_examples

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install poetry
    # poetry install

    # Convert single to double quotes
    RUN uv run ruff check . --select Q --fix
    # Remove unused imports
    RUN uv run ruff check . --select F --fix
    # Sort imports
    RUN uv run ruff check . --select I --fix
    # Format code
    RUN uv run ruff format .

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN uv run ruff format . --check --diff

# Ignore errors via "# noqa: F841"
lint:
    FROM +install-dev
    RUN uv run ruff check .

# Ignore errors via "# pyre-fixme[11]"
pyre:
    FROM +install-dev
    COPY .pyre_configuration /root/fastapi_server/.pyre_configuration
    RUN uv run pyre

pytest:
    FROM +install-dev
    RUN poetry run pytest

pre-commit:
    BUILD +format-check
    BUILD +lint
    BUILD +pyre

all:
    BUILD +pre-commit
    BUILD +pytest
