VERSION 0.6
# earthly +all --PYTHONVERSION=3.11
ARG PYTHONVERSION=3.11
FROM python:${PYTHONVERSION}-slim
WORKDIR /root/python_examples

# Run local example python file
start-dev:
    # Run on host system instead of inside a container
    LOCALLY
    RUN poetry run python main.py

install-dev:
    RUN pip install poetry --no-cache-dir
    COPY poetry.lock pyproject.toml ./
    RUN poetry install
    COPY . /root/python_examples

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install poetry
    # poetry install

    # Convert single to double quotes
    RUN poetry run ruff check . --select Q --fix
    # Remove unused imports
    RUN poetry run ruff check . --select F --fix
    # Sort imports
    RUN poetry run ruff check . --select I --fix
    # Format code
    RUN poetry run yapf -ir .

# Check if imports are unused
remove-unused-imports-check:
    FROM +install-dev
    RUN poetry run ruff check . --select F

# Check if imports require reordering
sort-imports-check:
    FROM +install-dev
    RUN poetry run ruff check . --select I

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN poetry run yapf -dr .

# Ignore errors via "# Ignore F841"
lint:
    FROM +install-dev
    RUN poetry run ruff check .

# Ignore errors via "# pyre-fixme[11]"
pyre:
    FROM +install-dev
    RUN poetry run pyre

pytest:
    FROM +install-dev
    RUN poetry run pytest

all:
    BUILD +remove-unused-imports-check
    BUILD +sort-imports-check
    BUILD +format-check
    BUILD +lint
    BUILD +pyre
    BUILD +pytest
