# To install hooks:
# poetry run pre-commit install
# To update hooks:
# poetry run pre-commit autoupdate
# To run hooks:
# poetry run pre-commit run --all-files --hook-stage push

# This removes comments which is unwanted
#- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#  rev: v2.1.0
#  hooks:
#  - id: pretty-format-toml
#    args: [--autofix]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  # As the name says
  - id: double-quote-string-fixer
  # Check yaml files like this one and github actions if they are valid
  - id: check-yaml
  # Check toml files like pyproject.toml if it is valid
  - id: check-toml
  # Check if python files are valid
  - id: check-ast
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  # Check for bad code
  - id: python-no-eval
  - id: python-no-log-warn
  # Enforce type annotation instead of comment annotation
  - id: python-use-type-annotations

# Autoformat yaml files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

# Check github action workflow files
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.18.4
  hooks:
  - id: check-github-workflows

- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

# Detect functions and variables that are never used
#- repo: https://github.com/asottile/dead
#  rev: v1.4.0
#  hooks:
#  - id: dead

#- repo: local
#  hooks:
#  # Install earthly requirements
#  - id: earthly
#    name: Install earthly requirements
#    stages: [push]
#    language: system
#    entry: earthly +install-all --verbose true
#    pass_filenames: false

  # Check formatting, lint, test
#  - id: earthly
#    name: Run earthly
#    stages: [push]
#    language: system
#    entry: earthly +all --verbose true
#    pass_filenames: false

#  - id: pytest-cov
#    name: pytest
#    stages: [push]
#    language: system
#    entry: poetry run pytest --cov=. --cov-fail-under=100
#    types: [python]
#    pass_filenames: false
