# Example copied from https://github.com/simplejson/simplejson/blob/master/.travis.yml
language: python


# Most tests run in container mode because it's faster to start up,
# but a few below use different configurations (as of July 2018
# only trusty is available in containers).

matrix:
      include:
            - os: linux
            dist: trusty
            sudo: false
            python: "3.6"

            - os: linux
            dist: trusty
            sudo: false
            python: "3.7"

            - os: linux
            dist: trusty
            sudo: false
            python: "3.7-dev"

            - os: linux
            dist: trusty
            sudo: false
            python: "3.8-dev"

      allow_failures:
            - python: "3.7-dev"
            - python: "3.8-dev"


install:
      - pip install --upgrade pip
      - pip install --upgrade pipenv
      - pipenv install --dev

script:
#      Test only a single file:
#      - pipenv run pytest tests/test_functions.py
#      Test the whole folder of test files:
      - pipenv run pytest tests/
