language: python

# Most tests run in container mode because it's faster to start up,
# but a few below use different configurations (as of July 2018
# only trusty is available in containers).
dist: trusty
sudo: false

jobs:
    include:
        - python: "3.6"
        - python: "3.7"
        - python: "3.7-dev"
        - python: "3.8-dev"
        - python: "3.9-dev"

install:
    - "pipenv install --dev"

script:
#    Test only a single file:
#    - "pipenv run pytest tests/test_functions.py"
#    Test the whole folder of test files:
    - "pipenv run pytest tests/"

matrix:
    allow_failures:
        - python: "3.7-dev"
        - python: "3.8-dev"
        - python: "3.9-dev"