language: python
os: linux
dist: xenial
sudo: false


# See: https://docs.travis-ci.com/user/build-matrix/
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"

  # Builds that are allowed to fail
  allow_failures:
    - python: "3.8"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"

  # Now, the build result will be determined as soon as all the required jobs finish, based on these results, while the rest of the allow_failures jobs continue to run.
  fast_finish: true

install:
  - "pip install --upgrade --user pip"
  - "pip install --upgrade --user pipenv"
  - "pipenv install --dev"

script:
#  Test only a single file:
#  - "pipenv run pytest tests/test_functions.py"
#  Test the whole folder of test files:
  - "pipenv run pytest tests/"