language: python
dist: xenial
sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      python: "3.6"
      sudo: false
    - os: linux
      dist: xenial
      python: "3.7"
      sudo: false
    - os: linux
      dist: xenial
      python: "3.8-dev"
      sudo: false

  allow_failures:
    - python: "3.8-dev"

install:
#  - "pip install --upgrade pip"
#  - "pip install --upgrade pipenv"
  - "pipenv install --dev"

script:
#  Test only a single file:
#  - "pipenv run pytest tests/test_functions.py"
#  Test the whole folder of test files:
  - "pipenv run pytest tests/"
