# Use http://www.yamllint.com/
# to validate .yml file

sudo: required
language: python
services: docker

jobs:
  # Now, the build result will be determined as soon as all the required jobs finish, based on these results, while the rest of the allow_failures jobs continue to run.
  fast_finish: true

  # Jobs that are allowed to fail
  allow_failures:
    - stage: test python 3.8

  # Jobs that are being run
  include:
    - stage: test python 3.6
      script:
        # Pull docker image, this step could be skipped
        - docker pull python:3.6-slim
        # Create docker container called "app" from image "python:3.6-slim", the "-alpine" versions have no "bash" installed so you can't do "cd /root/my_folder"
        - docker run -it -d --name app python:3.6-slim
        # List contents of current folder
        - ls
        # Copy repository files and folders to docker container
        - docker cp . app:/root/template
        # List contents of container
        - docker exec app ls /root/template
        # Upgrade pipenv (and implicitly pip)
        - docker exec app pip install --upgrade pipenv
        # Change directory, create pipenv virtual environment and install dev packages from Pipfile for testing
        # Command origins from here: https://stackoverflow.com/a/28037991/10882657
        - docker exec -i app bash -c "cd /root/template && pipenv install --dev"
        # Change directory and run tests
        - docker exec -i app bash -c "cd /root/template && pipenv run pytest tests/ --hypothesis-show-statistics"
        # Shut down and remove container
        - docker rm -f app

    - stage: test python 3.7
      script:
        - docker pull python:3.7-slim
        - docker run -it -d --name app python:3.7-slim
        - docker cp . app:/root/template
        - docker exec app pip install --upgrade pipenv
        # Specify python version in the install progress because it is different from the required version "python 3.6" according to the pipfile
        # The version will only have to be specified here, because this will create a new virtual environment. The run command in the next line line will then use the existing environment
        - docker exec -i app bash -c "cd /root/template && pipenv install --dev --python 3.7"
        # Dont have to specify python version here
        - docker exec -i app bash -c "cd /root/template && pipenv run pytest tests/ --hypothesis-show-statistics"
        - docker rm -f app

    - stage: test python 3.8
      script:
        # TODO: Change to normal python 3.8 version once 3.8 is released
        - docker pull python:3.8-rc-slim
        - docker run -it -d --name app python:3.8-rc-slim
        - docker cp . app:/root/template
        - docker exec app pip install --upgrade pipenv
        - docker exec -i app bash -c "cd /root/template && pipenv install --dev --python 3.8"
        - docker exec -i app bash -c "cd /root/template && pipenv run pytest tests/ --hypothesis-show-statistics"
        - docker rm -f app



# Testing using just python environments without docker:

#language: python
#sudo: false
## Defining it at the top will override it from default (trusty) to xenial
## Xenial allows python 3.7 and dev versions of python
## Also trusty is deprecated, see: https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
#dist: xenial
#
#
## See: https://docs.travis-ci.com/user/build-matrix/
#matrix:
#  include:
#    - python: "3.6"
#      os: linux
#
#    - python: "3.7"
#      os: linux
#
#    # TODO: uncomment when 3.8 is released
##    - python: "3.8"
##      os: linux
#
#    - python: "3.6-dev"
#      os: linux
#
#    - python: "3.7-dev"
#      os: linux
#
#    - python: "3.8-dev"
#      os: linux
#
#
#  # Builds that are allowed to fail
#  allow_failures:
#    - python: "3.8"
#    - python: "3.6-dev"
#    - python: "3.7-dev"
#    - python: "3.8-dev"
#
#  # Now, the build result will be determined as soon as all the required jobs finish, based on these results, while the rest of the allow_failures jobs continue to run.
#  fast_finish: true
#
#
#install:
#  # Implicitly also upgrades pip version
#  - "pip install --upgrade pipenv"
#  - "pipenv install --dev"
#
#
#script:
#  - python --version
##  Test only a single file:
##  - "pipenv run pytest tests/test_functions.py"
##  Test the whole folder of test files:
#  - "pipenv run pytest tests/"