extends: default
yaml-files: ['*.yaml', '*.yml']
rules:
  document-start: disable
  truthy: disable
  line-length: {max: 80}
  comments-indentation: enable
ignore: |
  .venv
  .venv/**
  node_modules
  node_modules/**
  ansible/**
