[tool.poetry]
name = "burny_test_template"
version = "0.1.0"
description = ""
authors = ["BuRny <gamingburny@gmail.com>"]
packages = [
    { include = "burny_test_template/*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
# Numeric python
numpy = "^1.20.3"
# Improve performance by writing C or C++ similar code
cython = "^3.0.0a8"
# Write and read classes to/from json
dataclasses-json = "^0.5.4"
# Network access
aiohttp = "^3.7.3"
# Required by aiohttp on windows?
idna-ssl = "^1.1.0"
# Simple logger
loguru = "^0.5.3"
# Required by loguru on windows?
aiocontextvars = "^0.2.2"
atomicwrites = "^1.3.0"
contextvars = "^2.4"
win32-setctime = "^1.0.3"
# Image library
pillow = "^8.2.0"
# Better / easier datetime library
pendulum = "^2.1.2"
# Easier nested dictionary manipulation
dpath = "^2.0.1"
# File watcher
watchgod = "^0.7"
# Database with ORM
SQLAlchemy = "^1.4.20"
# Simple database that operates on dictionaries
tinydb = "^4.5.0"

[tool.poetry.dev-dependencies]
# Autoformatter
yapf = "^0.31.0"
# Linting
pylint = "^2.8.3"
# Test library
pytest = "^6.2.2"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
pytest-benchmark = "^3.4.1"
# Type checking
mypy = "^0.910"
# Requirement for pytest < 3.8
importlib_metadata = "^1.7.0"
# Statistical testing
hypothesis = "^6.14.2"
# Cyclomatic complexity checker
radon = "^5.0.1"
# Function profiler, checks how often functions get called
snakeviz = "^2.1.0"
# Line profiler, unable to install on windows?
# line_profiler = "^3.0.2"
# Required by line_profiler
# ipython = "^7.16.1"
# Enable pre commit hooks
pre-commit = "^2.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
