[tool.poetry]
name = "burny_test_template"
version = "0.1.0"
description = ""
authors = ["BuRny <gamingburny@gmail.com>"]
packages = [
    { include = "burny_test_template/*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
# Numeric python
numpy = "^1.20.1"
# Improve performance by writing C or C++ similar code
cython = "^3.0a6"
# Write and read classes to/from json
dataclasses-json = "^0.5.1"
# Network access
aiohttp = "^3.7.3"
# Required by aiohttp on windows?
idna-ssl = "^1.1.0"
# Simple logger
loguru = "^0.5.3"
# Required by loguru on windows?
aiocontextvars = "^0.2.2"
atomicwrites = "^1.3.0"
contextvars = "^2.4"
win32-setctime = "^1.0.3"
# Image library
pillow = "^8.1.0"
# Better / easier datetime library
pendulum = "^2.1.2"
dpath = "^2.0.1"
mypy = "^0.812"
watchgod = "^0.7"

[tool.poetry.dev-dependencies]
# Test library
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"
# Requirement for pytest < 3.8
importlib_metadata = "^1.7.0"
# Statistical testing
hypothesis = "^6.2.0"
# Cyclomatic complexity checker
radon = "^4.3.2"
# Function profiler, checks how often functions get called
snakeviz = "^2.1.0"
# Line profiler, unable to install on windows?
# line_profiler = "^3.0.2"
# Required by line_profiler
# ipython = "^7.16.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
