/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/rick_morty": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Read Users */
        get: operations["read_users_api_rick_morty_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/hello_world": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Json Text */
        get: operations["json_text_api_hello_world_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/login": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get Login Status
         * @description Check if user is logged in by reading cookies.
         *     Returns user info if logged in, None otherwise.
         */
        get: operations["get_login_status_login_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/logout": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Logout
         * @description Clear all authentication cookies and redirect to login page.
         */
        get: operations["logout_logout_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/login/twitch": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Twitch Login Callback
         * @description Handle Twitch OAuth callback.
         *     If code provided, exchange for token and set cookie.
         *     If already logged in, redirect to login page.
         */
        get: operations["twitch_login_callback_login_twitch_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/login/github": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Github Login Callback
         * @description Handle GitHub OAuth callback.
         *     If code provided, exchange for token and set cookie.
         *     If already logged in, redirect to login page.
         */
        get: operations["github_login_callback_login_github_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/login/google": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Google Login Callback
         * @description Handle Google OAuth callback.
         *     Currently returns a placeholder response.
         */
        get: operations["google_login_callback_login_google_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/login/twitch/start": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Start Twitch Login
         * @description Start Twitch OAuth flow - redirects to Twitch authorization page.
         */
        get: operations["start_twitch_login_login_twitch_start_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/login/github/start": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Start Github Login
         * @description Start GitHub OAuth flow - redirects to GitHub authorization page.
         */
        get: operations["start_github_login_login_github_start_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/parse_replay": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Parse Replay File
         * @description Parse a StarCraft II replay file and return the parsed data as JSON.
         *
         *     The frontend handles all filtering, renaming, and zipping locally.
         */
        post: operations["parse_replay_file_api_parse_replay_post"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List Books
         * @description List all non-deleted books with chapter counts.
         */
        get: operations["list_books_api_audiobook_books_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get Book
         * @description Get a single book with its chapters.
         *     Returns 404 if not found.
         *     Generates presigned URLs for chapters with audio.
         *     Uses optimized SQL query to get global queue position.
         */
        get: operations["get_book_api_audiobook_books__book_id__get"]
        put?: never
        post?: never
        /**
         * Delete Book
         * @description Soft delete a book and clear queued status on its chapters.
         *     Returns 404 if not found.
         */
        delete: operations["delete_book_api_audiobook_books__book_id__delete"]
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/chapters/status": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get Chapter Status
         * @description Get status for specific chapters without full book data.
         *     Accepts comma-separated chapter numbers via query param 'chapter_numbers'.
         *     Returns only the status fields (queue position, converting, has_audio).
         */
        get: operations["get_chapter_status_api_audiobook_books__book_id__chapters_status_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/upload": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Upload Epub
         * @description Upload an epub file, parse it, and create book/chapter records.
         *     Returns 400 if not an epub, 201 on success.
         */
        post: operations["upload_epub_api_audiobook_upload_post"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/voices": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List Voices
         * @description List all available TTS voices.
         */
        get: operations["list_voices_api_audiobook_voices_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/audio": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /**
         * Delete All Audio
         * @description Delete all generated audio for a book.
         */
        delete: operations["delete_all_audio_api_audiobook_books__book_id__audio_delete"]
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/chapters/{chapter_id}/queue": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Queue Chapter
         * @description Queue a chapter for audio conversion.
         *     Sets queued timestamp and stores audio settings.
         */
        post: operations["queue_chapter_api_audiobook_books__book_id__chapters__chapter_id__queue_post"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/chapters/{chapter_id}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /**
         * Delete Chapter Audio
         * @description Delete the generated audio for a chapter.
         *     Removes the audio from Garage and clears the queued/audio fields.
         */
        delete: operations["delete_chapter_audio_api_audiobook_books__book_id__chapters__chapter_id__delete"]
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/title": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        /**
         * Update Book Title
         * @description Update the custom title for a book.
         */
        put: operations["update_book_title_api_audiobook_books__book_id__title_put"]
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/author": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        /**
         * Update Book Author
         * @description Update the custom author for a book.
         */
        put: operations["update_book_author_api_audiobook_books__book_id__author_put"]
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/queue-all": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Queue All Chapters
         * @description Queue all chapters of a book for audio conversion.
         */
        post: operations["queue_all_chapters_api_audiobook_books__book_id__queue_all_post"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/audiobook/books/{book_id}/download": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Download Book
         * @description Get a download URL for the entire book (all chapters as a single audio file).
         *     Returns 400 if not all chapters have audio.
         */
        get: operations["download_book_api_audiobook_books__book_id__download_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/raceroom/tracks": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get Tracks
         * @description Get all available tracks.
         */
        get: operations["get_tracks_api_raceroom_tracks_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/raceroom/times": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get Times
         * @description Get best times with optional filters.
         */
        get: operations["get_times_api_raceroom_times_get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/replay_comparer/parse_replay": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Parse Replay File */
        post: operations["parse_replay_file_api_replay_comparer_parse_replay_post"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Root
         * @description Health‑check endpoint returning a simple JSON payload.
         */
        get: operations["root__get"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        /** Body_parse_replay_file_api_parse_replay_post */
        Body_parse_replay_file_api_parse_replay_post: {
            /** File */
            file: string
        }
        /** Body_parse_replay_file_api_replay_comparer_parse_replay_post */
        Body_parse_replay_file_api_replay_comparer_parse_replay_post: {
            /**
             * Replay File
             * @description The SC2Replay file to parse
             */
            replay_file: string
            /**
             * Replay Tick
             * @description Gameloop tick interval (e.g. 224 for 22.4 seconds)
             */
            replay_tick: string
        }
        /** Body_upload_epub_api_audiobook_upload_post */
        Body_upload_epub_api_audiobook_upload_post: {
            /** File */
            file: string
        }
        /** BookListItem */
        BookListItem: {
            /** Id */
            id: number
            /** Uploaded By */
            uploaded_by: string
            /** Book Title */
            book_title: string
            /** Book Author */
            book_author: string
            /** Custom Book Title */
            custom_book_title?: string | null
            /** Custom Book Author */
            custom_book_author?: string | null
            /** Chapter Count */
            chapter_count: number
            /**
             * Upload Date
             * Format: date-time
             */
            upload_date: string
        }
        /** BookWithChapters */
        BookWithChapters: {
            book: components["schemas"]["BookListItem"]
            /** Chapters */
            chapters: components["schemas"]["ChapterDetail"][]
            /** Available Voices */
            available_voices: string[]
        }
        /** ChapterDetail */
        ChapterDetail: {
            /** Id */
            id: number
            /** Book Id */
            book_id: number
            /** Number In Queue */
            number_in_queue?: number | null
            /** Is Converting */
            is_converting: boolean
            /** Has Audio */
            has_audio: boolean
            /** Chapter Title */
            chapter_title: string
            /** Chapter Number */
            chapter_number: number
            /** Sentence Count */
            sentence_count: number
            /** Minio Object Name */
            minio_object_name?: string | null
            /**
             * Minio Presigned Url
             * @default
             */
            minio_presigned_url: string
        }
        /** DeleteResponse */
        DeleteResponse: {
            /** Deleted */
            deleted: boolean
        }
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][]
        }
        /** QueueChapterRequest */
        QueueChapterRequest: {
            /** Value */
            value: string
        }
        /** QueueResponse */
        QueueResponse: {
            /** Queued */
            queued: boolean
        }
        /** UploadSuccess */
        UploadSuccess: {
            /** Id */
            id: number
            /** Title */
            title: string
        }
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[]
            /** Message */
            msg: string
            /** Error Type */
            type: string
            /** Input */
            input?: unknown
            /** Context */
            ctx?: Record<string, never>
        }
        /** VoiceOption */
        VoiceOption: {
            /** Value */
            value: string
            /** Label */
            label: string
            /** Engine */
            engine: string
            /** Locale */
            locale: string
            /** Gender */
            gender: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    read_users_api_rick_morty_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    json_text_api_hello_world_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    get_login_status_login_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    logout_logout_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    twitch_login_callback_login_twitch_get: {
        parameters: {
            query?: {
                code?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    github_login_callback_login_github_get: {
        parameters: {
            query?: {
                code?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    google_login_callback_login_google_get: {
        parameters: {
            query?: {
                code?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    start_twitch_login_login_twitch_start_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    start_github_login_login_github_start_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    parse_replay_file_api_parse_replay_post: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_replay_file_api_parse_replay_post"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    list_books_api_audiobook_books_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["BookListItem"][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    get_book_api_audiobook_books__book_id__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["BookWithChapters"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    delete_book_api_audiobook_books__book_id__delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["DeleteResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    get_chapter_status_api_audiobook_books__book_id__chapters_status_get: {
        parameters: {
            query: {
                chapter_numbers: string
            }
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ChapterDetail"][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    upload_epub_api_audiobook_upload_post: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_epub_api_audiobook_upload_post"]
            }
        }
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["UploadSuccess"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    list_voices_api_audiobook_voices_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["VoiceOption"][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    delete_all_audio_api_audiobook_books__book_id__audio_delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["DeleteResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    queue_chapter_api_audiobook_books__book_id__chapters__chapter_id__queue_post: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
                chapter_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueChapterRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["QueueResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    delete_chapter_audio_api_audiobook_books__book_id__chapters__chapter_id__delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
                chapter_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["DeleteResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    update_book_title_api_audiobook_books__book_id__title_put: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown
                }
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["BookListItem"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    update_book_author_api_audiobook_books__book_id__author_put: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown
                }
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["BookListItem"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    queue_all_chapters_api_audiobook_books__book_id__queue_all_post: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueChapterRequest"]
            }
        }
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["QueueResponse"]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    download_book_api_audiobook_books__book_id__download_get: {
        parameters: {
            query?: never
            header?: never
            path: {
                book_id: number
            }
            cookie?: {
                twitch_access_token?: string | null
                github_access_token?: string | null
                google_access_token?: string | null
            }
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        [key: string]: unknown
                    }
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    get_tracks_api_raceroom_tracks_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
        }
    }
    get_times_api_raceroom_times_get: {
        parameters: {
            query?: {
                /** @description Filter by track ID */
                track_id?: number | null
                /** @description Filter by start date (ISO format) */
                start_date?: string | null
                /** @description Filter by end date (ISO format) */
                end_date?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    parse_replay_file_api_replay_comparer_parse_replay_post: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_replay_file_api_replay_comparer_parse_replay_post"]
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"]
                }
            }
        }
    }
    root__get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        [key: string]: unknown
                    }
                }
            }
        }
    }
}
