# Rename me to "SECRETS.toml"
api_id = 123456789
api_hash = "your_api_hash"
stage = "DEV"

# Which channels to download from
channel_ids = ["channel_name"]
# Which types to download
media_types = ["audio", "photo", "video"]
# Download folder
output_folder = "/your/download/folder"
# Parallel downloads
parallel_downloads_count = 5

# Filters
# Photo
photo_min_file_size_bytes = 0
photo_max_file_size_bytes = 4_000_000_000
photo_min_width = 0
photo_max_width = 1_000_000
photo_min_height = 0
photo_max_height = 1_000_000
# Video
video_min_file_size_bytes = 0
video_max_file_size_bytes = 4_000_000_000
video_min_file_duration_seconds = 0
video_max_file_duration_seconds = 4_000_000_000
video_min_width = 0
video_max_width = 1_000_000
video_min_height = 0
video_max_height = 1_000_000
# Audio
audio_min_file_size_bytes = 0
audio_max_file_size_bytes = 4_000_000_000
audio_min_file_duration_seconds = 0
audio_max_file_duration_seconds = 4_000_000_000