# https://doc.cocalc.com/index.html
# https://github.com/sagemathinc/cocalc-docker
# Execute with
# ansible-playbook cocalc_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Stop, remove image, and start cocalc service
  hosts: my_servers
  vars:
    USERNAME: '{{ secrets.COCALC.USERNAME }}'
  tasks:
  - name: Create group
    ansible.builtin.group:
      name: '{{ USERNAME }}'
      state: present

  - name: Create user
    ansible.builtin.user:
      name: '{{ USERNAME }}'
      groups:
      - '{{ USERNAME }}'
      - docker
      shell: '{{ secrets.DEFAULT_SHELL }}'

  - name: Get user id
    ansible.builtin.shell:
      cmd: id {{ USERNAME }} -u
    register: USER_ID

  - name: Get group id
    ansible.builtin.shell:
      cmd: id {{ USERNAME }} -g
    register: GROUP_ID

  - name: Print user id
    ansible.builtin.debug:
      var: USER_ID.stdout
      verbosity: 0

  - name: Print group id
    ansible.builtin.debug:
      var: GROUP_ID.stdout
      verbosity: 0

  - name: Create systemd file
    template:
      src: cocalc.service
      dest: /etc/systemd/system/{{ USERNAME }}.service
      owner: '{{ USER_ID.stdout }}'
      group: '{{ GROUP_ID.stdout }}'

  - name: Stop cocalc service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Remove cocalc container
    community.docker.docker_container:
      name: cocalc
      state: absent
      image: sagemathinc/cocalc-v2:latest

  - name: Start cocalc service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      daemon_reload: true
      enabled: true

  - name: Print reminder to disallow signup
    ansible.builtin.debug:
      msg: Remember go to the admin page and create registration token to disallow signup for everyone

  - name: Print reminder to make admin user
    ansible.builtin.debug:
      msg: Create the first user by signing up, then run 'docker exec -it cocalc bash' and '/cocalc/src/scripts/make-user-admin <your-email>'

