VERSION 0.6
# earthly +all --NODEVERSION=18
ARG NODEVERSION=18 # 14, 16, or 18
FROM node:${NODEVERSION}-slim
WORKDIR /root/bored_gems

install-dev:
    COPY package.json package-lock.json ./
    RUN npm install
    COPY src /root/bored_gems/src
    COPY static /root/bored_gems/static

install-prod:
    COPY package.json package-lock.json ./
    RUN npm install --omit=dev
    COPY src /root/bored_gems/src
    COPY static /root/bored_gems/static

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # npm i

    # Format code
    RUN npm run format

format-check:
    FROM +install-dev
    COPY .prettierrc ./
    RUN npm run format:check

lint:
    FROM +install-dev
    COPY .eslintrc.cjs ./
    RUN npm run lint

test:
    COPY package.json package-lock.json ./
    RUN npm install
    RUN npx playwright install --with-deps chromium
    COPY src /root/bored_gems/src
    COPY static /root/bored_gems/static
    COPY tests /root/bored_gems/tests
    # Why is tsconfig.json not needed here?
    COPY playwright.config.ts svelte.config.js vite.config.js ./
    RUN npm run test

build:
    FROM +install-prod
    # Why is tsconfig.json not needed here?
    COPY svelte.config.js vite.config.js ./
    RUN npm run build
    SAVE ARTIFACT build AS LOCAL ./

all:
    BUILD +format-check
    # TODO Fix me
    #BUILD +lint
    BUILD +test
    BUILD +build
