# https://hub.docker.com/_/sonarqube
# https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/
# https://docs.sonarsource.com/sonarqube/9.9/devops-platform-integration/github-integration/
# Execute with
# ansible-playbook sonarqube_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.SONARQUBE.USERNAME }}"
    SUBDOMAIN: "{{ secrets.SONARQUBE.SUBDOMAIN }}"
    APPLICATION_PORT: "9000"
  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{ USERNAME }}"
        state: present

    - name: Create user
      ansible.builtin.user:
        name: "{{ USERNAME }}"
        groups:
          - "{{ USERNAME }}"
          - docker
        shell: "{{ secrets.DEFAULT_SHELL }}"

    - name: Set vm.max_map_count
      ansible.posix.sysctl:
        name: vm.max_map_count
        value: "524288"
        state: present

    - name: Set fs.file-max
      ansible.posix.sysctl:
        name: fs.file-max
        value: "131072"
        state: present

    - name: Copy docker-compose.yml file
      template:
        src: docker-compose.yml
        dest: /home/{{ USERNAME }}/docker-compose.yml

    - name: Run `docker-compose up` again
      community.docker.docker_compose_v2:
        project_src: /home/{{ USERNAME }}
        pull: always

    - name: Print reminder to change admin password
      ansible.builtin.debug:
        msg: Initial login is 'admin' with password 'admin'. Change it immediately!
