version: '3'

networks:
  '{{secrets.TRAFIK_NETWORK}}':
    external: true

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud_server
    hostname: owncloud_server
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    labels:
    - traefik.enable=true
    - traefik.http.routers.{{ secrets.OWNCLOUD.USERNAME }}.rule=Host(`{{ secrets.OWNCLOUD.USERNAME }}.{{ secrets.MY_DOMAIN }}`)
    - traefik.http.services.{{ secrets.OWNCLOUD.USERNAME }}.loadbalancer.server.port=8080
    - traefik.http.routers.{{ secrets.OWNCLOUD.USERNAME }}.tls=true
    - traefik.http.routers.{{ secrets.OWNCLOUD.USERNAME }}.tls.certresolver=production
    - traefik.http.routers.{{ secrets.OWNCLOUD.USERNAME }}.middlewares=authelia@docker
    depends_on:
    - mariadb
    - redis
    environment:
    - PUID="{{ USER_ID.stdout }}"
    - PGID="{{ GROUP_ID.stdout }}"
    - OWNCLOUD_DOMAIN={{ secrets.OWNCLOUD.USERNAME }}.{{ secrets.MY_DOMAIN }}
    - OWNCLOUD_TRUSTED_DOMAINS="localhost,{{ secrets.OWNCLOUD.USERNAME }}.{{ secrets.MY_DOMAIN }}
    - OWNCLOUD_DB_TYPE=mysql
    - OWNCLOUD_DB_NAME=owncloud
    - OWNCLOUD_DB_USERNAME=owncloud
    - OWNCLOUD_DB_PASSWORD=owncloud
    - OWNCLOUD_DB_HOST=mariadb
    - OWNCLOUD_ADMIN_USERNAME={{ secrets.OWNCLOUD.ADMIN_USERNAME }}
    - OWNCLOUD_ADMIN_PASSWORD={{ secrets.OWNCLOUD.ADMIN_PASSWORD }}
    - OWNCLOUD_MYSQL_UTF8MB4=true
    - OWNCLOUD_REDIS_ENABLED=true
    - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: [CMD, /usr/bin/healthcheck]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
    - ./data:/mnt/data

  mariadb:
    image: mariadb:10.6 # minimum required ownCloud version is 10.9
    container_name: owncloud_mariadb
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    environment:
    - MYSQL_ROOT_PASSWORD={{ secrets.OWNCLOUD.MYSQL_ROOT_PASSWORD }}
    - MYSQL_USER={{ secrets.OWNCLOUD.MYSQL_USER }}
    - MYSQL_PASSWORD={{ secrets.OWNCLOUD.MYSQL_PASSWORD }}
    - MYSQL_DATABASE={{ secrets.OWNCLOUD.MYSQL_DATABASE }}
    command: [--max-allowed-packet=128M, --innodb-log-file-size=64M]
    healthcheck:
      test: [CMD, mysqladmin, ping, -u, root, '--password={{ secrets.OWNCLOUD.MYSQL_PASSWORD }}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    command: [--databases, '1']
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - redis:/data
