---
# Rescan all files (for example when uploading file manually) with:
# https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#the-filesscan-command
# docker compose exec owncloud occ files:scan --all
# Dont forget to change owner to owncloud user
networks:
  owncloud_mariadb:
    driver: bridge
  pangolin_newt:
    external: true
services:
  owncloud:
    # https://hub.docker.com/r/owncloud/server/tags
    image: owncloud/server:10.16.1
    container_name: owncloud_server
    hostname: owncloud_server
    networks:
      - owncloud_mariadb
      - pangolin_newt
    restart: unless-stopped
    labels:
      - pangolin.public-resources.cloud.name=Owncloud
      - pangolin.public-resources.cloud.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.cloud.protocol=http
      - pangolin.public-resources.cloud.auth.sso-enabled=false
      - pangolin.public-resources.cloud.targets[0].site=local
      - pangolin.public-resources.cloud.targets[0].method=http
      - pangolin.public-resources.cloud.targets[0].hostname=owncloud_server
      - pangolin.public-resources.cloud.targets[0].port={{ APPLICATION_PORT }}
    depends_on:
      - mariadb
    environment:
      - OWNCLOUD_DOMAIN={{ secrets.OWNCLOUD.USERNAME }}.{{ secrets.MY_DOMAIN }}
      - OWNCLOUD_TRUSTED_DOMAINS="localhost,{{ secrets.OWNCLOUD.USERNAME }}.{{ secrets.MY_DOMAIN }}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME={{ secrets.OWNCLOUD.MYSQL_DATABASE }}
      - OWNCLOUD_DB_USERNAME={{ secrets.OWNCLOUD.MYSQL_USER }}
      - OWNCLOUD_DB_PASSWORD={{ secrets.OWNCLOUD.MYSQL_PASSWORD }}
      - OWNCLOUD_DB_HOST=owncloud_mariadb
      - OWNCLOUD_ADMIN_USERNAME={{ secrets.OWNCLOUD.ADMIN_USERNAME }}
      - OWNCLOUD_ADMIN_PASSWORD={{ secrets.OWNCLOUD.ADMIN_PASSWORD }}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=false
      - OWNCLOUD_REDIS_HOST=owncloud_redis
    healthcheck:
      test:
        - CMD
        - /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/mnt/data
  mariadb:
    image: mariadb:10.11  # minimum required ownCloud version is 10.9
    container_name: owncloud_mariadb
    hostname: owncloud_mariadb
    restart: unless-stopped
    networks:
      - owncloud_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD={{ secrets.OWNCLOUD.MYSQL_ROOT_PASSWORD }}
      - MYSQL_USER={{ secrets.OWNCLOUD.MYSQL_USER }}
      - MYSQL_PASSWORD={{ secrets.OWNCLOUD.MYSQL_PASSWORD }}
      - MYSQL_DATABASE={{ secrets.OWNCLOUD.MYSQL_DATABASE }}
    command:
      - --max-allowed-packet=128M
      - --innodb-log-file-size=64M
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -u
        - root
        - --password={{ secrets.OWNCLOUD.MYSQL_PASSWORD }}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql
