# Execute with
# ansible-playbook owncloud_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Stop, remove image, and start owncloud service
  hosts: my_servers
  vars:
    USERNAME: '{{ secrets.OWNCLOUD.USERNAME }}'
  tasks:
  - name: Stop owncloud service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Remove cloud-server container
    community.docker.docker_container:
      name: owncloud_server
      state: absent
      image: owncloud/server:latest

  - name: Remove cloud-db container
    community.docker.docker_container:
      name: owncloud_mariadb
      state: absent
      image: mariadb:10.6

  - name: Remove cloud-redis container
    community.docker.docker_container:
      name: owncloud_redis
      state: absent
      image: redis:6

  - name: Remove owncloud image
    community.docker.docker_image:
      name: owncloud/server
      tag: latest
      state: absent

  - name: Start owncloud service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      daemon_reload: true
      enabled: true
