---
networks:
  pangolin_newt:
    external: true
services:
  owncloud:
    image: agent0ai/agent-zero:latest
    container_name: agent_zero
    hostname: agent_zero
    networks:
      - pangolin_newt
    restart: unless-stopped
    volumes:
      - /media/ssd480/agentzero/usr:/a0/usr
      - /media/ssd480/shared/workspace:/a0/usr/projects
    labels:
      - pangolin.public-resources.agentzero.name=AgentZero
      - pangolin.public-resources.agentzero.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.agentzero.protocol=http
      - pangolin.public-resources.agentzero.auth.sso-enabled=true
      # - pangolin.public-resources.agentzero.auth.sso-roles[0]=jellyfin
      - pangolin.public-resources.agentzero.targets[0].method=http
      - pangolin.public-resources.agentzero.targets[0].port={{ APPLICATION_PORT }}
