---
x-services-fragments:
  webserver: &webserver
    image: burnysc2/fastapi_server:latest_dev
    pull_policy: never
    command: uv run --no-dev --directory src rio run --port 8000 --release --public
    restart: unless-stopped
    container_name: fastapi_server
    hostname: fastapi_server
    env_file:
      - .env
  convert_audiobook_worker: &convert_audiobook_worker
    image: burnysc2/fastapi_server:latest_dev
    pull_policy: never
    command:
      - sh
      - -c
      - uv run --no-dev python src/workers/convert_audiobook.py && sleep 1m
    env_file:
      - .env
    # Has no volume because all files are temporary
    # If changes occur, they will be saved in postgres or minio
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
    restart: always
services:
  # === PROD SETUP
  webserver:
    <<: *webserver
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.fastapi.name=Fastapi server
      - pangolin.public-resources.fastapi.full-domain=burnysc2.xyz
      - pangolin.public-resources.fastapi.protocol=http
      - pangolin.public-resources.fastapi.auth.sso-enabled=false
      - pangolin.public-resources.fastapi.targets[0].method=http
      - pangolin.public-resources.fastapi.targets[0].port=8000
      # Old routes
      # Redirect for www.burnysc2.xyz to burnysc2.xyz
      - traefik.http.routers.www-fastapi.rule=Host(`www.burnysc2.xyz`)
      - traefik.http.routers.www-fastapi.middlewares=redirect-to-non-www
      - traefik.http.routers.www-fastapi.tls=true
      - traefik.http.routers.www-fastapi.tls.certresolver=production
      - traefik.http.routers.www-fastapi.entryPoints=web,websecure
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\.burnysc2\.xyz/(.*)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://burnysc2.xyz/$${1}
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
      # Redirect for apidev.burnysc2.xyz to burnysc2.xyz
      - traefik.http.routers.apidev-fastapi.rule=Host(`apidev.burnysc2.xyz`)
      - traefik.http.routers.apidev-fastapi.middlewares=redirect-to-non-apidev
      - traefik.http.routers.apidev-fastapi.tls=true
      - traefik.http.routers.apidev-fastapi.tls.certresolver=production
      - traefik.http.routers.apidev-fastapi.entryPoints=web,websecure
      - traefik.http.middlewares.redirect-to-non-apidev.redirectregex.regex=^https?://apidev\.burnysc2\.xyz/(.*)
      - traefik.http.middlewares.redirect-to-non-apidev.redirectregex.replacement=https://burnysc2.xyz/$${1}
      - traefik.http.middlewares.redirect-to-non-apidev.redirectregex.permanent=true
    profiles:
      - prod

  # Responsible for converting text to audio
  convert_audiobook_worker:
    <<: *convert_audiobook_worker
    networks:
      - pangolin_newt
    profiles:
      - prod

  # Responsible for fetching raceroom stats
  raceroom_fetch_worker:
    <<: *convert_audiobook_worker
    command:
      - sh
      - -c
      - uv run --no-dev python src/workers/raceroom_fetch_records.py && sleep 1m
    networks:
      - pangolin_newt
    profiles:
      - prod

  # === DEV SETUP
  traefik:
    image: traefik:v3.6
    container_name: traefik
    networks:
      - fastapi_dev
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - ""
      - local_dev
  webserver_dev:
    <<: *webserver
    build: .
    pull_policy: build
    network_mode: host
    depends_on:
      - traefik
      - local_dev_minio
      - local_dev_rustfs
      - local_dev_postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`localhost`)
      - traefik.http.services.fastapi.loadbalancer.server.port=8000
    profiles:
      - local_dev
  local_dev_convert_audiobook_worker:
    <<: *convert_audiobook_worker
    build: .
    pull_policy: build
    depends_on:
      - local_dev_minio
      - local_dev_postgres
      - traefik
    network_mode: host
    profiles:
      - local_dev
  # local_dev_minio:
  #   container_name: fastapi_dev_minio
  #   hostname: fastapi_dev_minio
  #   # image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
  #   image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
  #   pull_policy: always
  #   command: minio server data --console-address ":9001"
  #   restart: unless-stopped
  #   labels:
  #     - traefik.enable=true
  #     # API
  #     - traefik.http.routers.minio.rule=Host(`minio.localhost`)
  #     - traefik.http.routers.minio.service=minio
  #     - traefik.http.services.minio.loadbalancer.server.port=9000
  #     # ADMIN LOGIN
  #     - traefik.http.routers.minioadmin.rule=Host(`minioadmin.localhost`)
  #     - traefik.http.routers.minioadmin.service=minioadmin
  #     - traefik.http.services.minioadmin.loadbalancer.server.port=9001
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   volumes:
  #     - dev_minio_data:/data
  #   environment:
  #     - MINIO_ROOT_USER=root
  #     - MINIO_ROOT_PASSWORD=rootroot
  #   profiles:
  #     - ""
  #     - local_dev
  #     - test
  local_dev_rustfs:
    image: rustfs/rustfs:latest
    container_name: fastapi_dev_rustfs
    hostname: fastapi_dev_rustfs
    restart: unless-stopped
    user: "10001:10001"
    ports:
      - 9000:9000 # S3 API
      - 9001:9001 # Admin API
    volumes:
      - dev_rustfs_data:/data
      - dev_rustfs_logs:/logs
    profiles:
      - ""
      - local_dev
      - test
    environment:
      - CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_EXTERNAL_ADDRESS=:9000
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
  local_dev_postgres:
    container_name: fastapi_dev_postgres
    hostname: fastapi_dev_postgres
    image: postgres:16-alpine
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.postgres.rule=Host(`postgres.localhost`)
      - traefik.http.services.postgres.loadbalancer.server.port=5432
    networks:
      - fastapi_dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastapi_server
    ports:
      - 5432:5432
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    profiles:
      - ""
      - local_dev
  local_dev_postgres_test:
    # This container is only used for running tests
    container_name: fastapi_dev_postgres_test
    hostname: fastapi_dev_postgres_test
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5433:5432
    profiles:
      - ""
      - test
  local_dev_pgadmin:
    # Connect via:
    # Address: fastapi_dev_postgres
    # Port: 5432
    # Username and password: root
    container_name: fastapi_dev_pgadmin
    hostname: fastapi_dev_pgadmin
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      - local_dev_postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    networks:
      - fastapi_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - dev_pgadmin_data:/var/lib/pgadmin
    profiles:
      - ""
      - local_dev
# TODO Background workers for transcription
networks:
  fastapi_dev:
    driver: bridge
  # '{{ secrets.TRAEFIK_NETWORK }}':
  #   name: '{{ secrets.TRAEFIK_NETWORK }}'
  #   external: true
  pangolin_newt:
    external: true
volumes:
  dev_minio_data: null
  dev_postgres_data: null
  dev_pgadmin_data: null
  dev_rustfs_data: null
  dev_rustfs_logs: null
