[project]
name = "src"
version = "0.1.0"
requires-python = ">=3.10, <3.15"
dependencies = [
    # Time management
    "arrow>=1.3.0",
    # xml parsing
    "beautifulsoup4>=4.12.3",
    # Epub Parsing
    "ebooklib>=0.18",
    # Web requests (sync + async)
    # "httpx>=0.27.2",
    # Websockets for httpx
    # "httpx-ws>=0.6.2",
    # Fastapi alternative https://docs.litestar.dev/latest/
    # "litestar[standard]>=2.12.1",
    # Simple logger
    "loguru>=0.7.2",
    # Analyse mp3 files in memory
    "mutagen>=1.47.0",
    # Language manipulation
    "nltk>=3.9.1",
    # Database
    "piccolo[postgres]>=1.27.0",
    # Dataclasses with type validation
    "pydantic>=2.9.2",
    # PDF Parsing
    # "pymupdf>=1.24.13",
    # Load .env files easily
    "python-dotenv>=1.0.1",
    # Audio generation
    "edge-tts>=6.1.18",
    # Zip files with low memory footprint
    "stream-zip>=0.0.83",
    # AWS S3
    # "minio>=7.2.15",
    "humanize>=4.11.0",
    # SC2 Replay Parser
    "sc2reader>=1.8.0",
    # "reflex==0.8.24.post1",
    # "streamlit>=1.52.2",
    "rio-ui>=0.11.1",
    # Async access to minio client
    "aioboto3>=15.5.0",
]

[tool.uv]
[dependency-groups]
dev = [
    "djlint>=1.36.4",
    # Property based testing
    "hypothesis>=6.118.8",
    # Info about the system
    "psutil>=6.1.0",
    # Type checker
    "pyrefly>=0.40.0",
    "pytest>=8.3.3",
    # Async await support
    "pytest-asyncio>=0.24.0",
    "pytest-benchmark>=5.1.0",
    # Set different env while testing
    "pytest-env>=1.1.5",
    # Mock requests
    "pytest-httpx>=0.33.0",
    "pytest-random-order>=1.1.1",
    # Linter and autoformat
    "ruff>=0.7.3",
    "sqlfluff>=3.3.1",
    "toml>=0.10.2",
    "pytest-databases[postgres]>=0.13.0",
    "pre-commit>=4.5.1",
    "types-aioboto3[full]>=15.5.0",
]

[tool.yapf]
based_on_style = "pep8"
column_limit = 120
split_arguments_when_comma_terminated = true
dedent_closing_brackets = true
allow_split_before_dict_value = false

[tool.pyrefly]
project_includes = ["src"]
project-excludes = [
    # Temp disable for those files and folders
    "**/workers/prevent_overflowing_audiobook_bucket.py",
    "**/workers/convert_audiobook.py",
    "**/_app.py",
    "**/components/**/*.py",
    "**/routes_/**/*.py",
]

# [tool.pyrefly.errors]
# bad-override = false

[tool.ruff]
target-version = 'py310'
line-length = 120

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
    "C4",  # flake8-comprehensions
    "E",   # Error
    "F",   # pyflakes
    "BLE", # flake8-blind-except
    # "I",   # isort
    "N",   # pep8-naming
    "PGH", # pygrep-hooks
    "PTH", # flake8-use-pathlib
    "SIM", # flake8-simplify
    "W",   # Warning
    "Q",   # flake8-quotes
    "YTT", # flake8-2020
    "UP",  # pyupgrade
    #    "A",  # flake8-builtins
]
ignore = ["SIM300"]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
pep8-naming.classmethod-decorators = ["pydantic.validator", "classmethod"]

[tool.sqlfluff.core]
dialect = "postgres"
max_line_length = 120
templater = "placeholder"
sql_file_exts = ".sql"
exclude_rules = "CP02,AL09,RF04"

[tool.sqlfluff.templater.placeholder]
# https://docs.sqlfluff.com/en/3.3.0/configuration/templating/placeholder.html
param_style = "ampersand" # { }

[tool.sqlfluff.indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[tool.sqlfluff.templater]
unwrap_wrapped_queries = true

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = true

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["test"]

[tool.pytest_env]
# Env variables to be used while tests run
STAGE = "test"
POSTGRES_CONNECTION_STRING = "postgresql://test:test@localhost:5433/test"
BACKEND_SERVER_URL = "http://localhost:8000"
MINIO_URL = "localhost:9000"
MINIO_ACCESS_TOKEN = "mylocaldevkey"
MINIO_SECRET_KEY = "mylocaldevpassword"
MINIO_AUDIOBOOK_BUCKET = "audiobooks-test"
MINIO_TELEGRAM_FILES_BUCKET = "telegram-files"
