VERSION 0.6
# earthly +all --NIMVERSION=1.6.14
ARG NIMVERSION=2.2.0-ubuntu
FROM nimlang/nim:${NIMVERSION}
WORKDIR /root/tsa

setup:
    COPY . /root/tsa
    RUN nimble install --depsOnly

run-local:
    # Run on host system instead of inside a container
    LOCALLY
    RUN nim r -d:release main.nim

run:
    FROM +setup
    RUN nim r -d:release main.nim

compile:
    FROM +setup
    RUN nimble c -d:ssl -d:release --opt:size -o:main src/main.nim

run-tests:
    FROM +setup
    RUN testament pattern "tests/*.nim"

all:
    BUILD +compile
    # BUILD +run-tests
