---
services:
  opencode:
    image: smanx/opencode
    container_name: opencode
    volumes:
      - /media/ssd480/opencode/config:/root/.config/opencode
      - /media/ssd480/opencode/data:/root/.local/share/opencode
      - /media/ssd480/opencode/workspace:/workspace
    networks:
      - pangolin_newt
    restart: unless-stopped
    labels:
      - pangolin.public-resources.opencode.name=OpenCode
      - pangolin.public-resources.opencode.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.opencode.protocol=http
      - pangolin.public-resources.opencode.auth.sso-enabled=true
      - pangolin.public-resources.opencode.targets[0].method=http
      - pangolin.public-resources.opencode.targets[0].port=4096
    # environment:
    #   - OPENCODE_HOSTNAME=0.0.0.0

networks:
  pangolin_newt:
    external: true
