---
networks:
  '{{secrets.TRAEFIK_NETWORK}}':
    external: true
  docmost-net:
    driver: bridge
services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'https://{{ secrets.DOCMOST.SUBDOMAIN
        }}.{{ secrets.MY_DOMAIN }}'
      APP_SECRET: '{{ secrets.DOCMOST.APP_SECRET }}'
      DATABASE_URL: 'postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    restart: unless-stopped
    volumes:
      - ./docmost:/app/data/storage
    networks:
      - '{{ secrets.TRAEFIK_NETWORK }}'
      - docmost-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ secrets.DOCMOST.USERNAME }}.rule=Host(`{{ secrets.DOCMOST.SUBDOMAIN
        }}.{{ secrets.MY_DOMAIN }}`)
      - traefik.http.services.{{ secrets.DOCMOST.USERNAME }}.loadbalancer.server.port={{
        APPLICATION_PORT }}
      - traefik.http.routers.{{ secrets.DOCMOST.USERNAME }}.tls=true
      - traefik.http.routers.{{ secrets.DOCMOST.USERNAME }}.tls.certresolver=production
      # - traefik.http.routers.{{ secrets.BOOKSTACK.USERNAME }}.middlewares=authelia@docker

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - docmost-net

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - docmost-net

volumes:
  docmost:
  db_data:
  redis_data:
