---
networks:
  pangolin_newt:
    external: true
services:
  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server --console-address ":9001" "data"
    restart: unless-stopped
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.minio.name=Minio server
      - pangolin.public-resources.minio.full-domain={{ secrets.MINIO.SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.minio.protocol=http
      - pangolin.public-resources.minio.auth.sso-enabled=false
      - pangolin.public-resources.minio.targets[0].site=local
      - pangolin.public-resources.minio.targets[0].method=http
      - pangolin.public-resources.minio.targets[0].port=9000
      - pangolin.public-resources.minio-admin.name=Minio server admin
      - pangolin.public-resources.minio-admin.full-domain={{ secrets.MINIO.ADMINSUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.minio-admin.protocol=http
      - pangolin.public-resources.minio-admin.auth.sso-enabled=true
      - pangolin.public-resources.minio-admin.targets[0].site=local
      - pangolin.public-resources.minio-admin.targets[0].method=http
      - pangolin.public-resources.minio-admin.targets[0].port=9001
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER={{ secrets.MINIO.MINIO_ROOT_USERNAME }}
      - MINIO_ROOT_PASSWORD={{ secrets.MINIO.MINIO_ROOT_PASSWORD }}
