---
networks:
  pangolin_newt:
    external: true
services:
  audiobookshelf:
    container_name: audiobookshelf
    hostname: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    restart: unless-stopped
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.audiobookshelf.name=Audiobookshelf
      - pangolin.public-resources.audiobookshelf.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.audiobookshelf.protocol=http
      - pangolin.public-resources.audiobookshelf.auth.sso-enabled=false
      - pangolin.public-resources.audiobookshelf.targets[0].method=http
      - pangolin.public-resources.audiobookshelf.targets[0].port={{ APPLICATION_PORT }}
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - '{{ secrets.AUDIOBOOKSHELF.MEDIA_FOLDER_AUDIOBOOKS }}:/audiobooks'
      - '{{ secrets.AUDIOBOOKSHELF.MEDIA_FOLDER_PODCASTS }}:/podcasts'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
