from __future__ import annotations

from enum import Enum


class Voices(Enum):
    ENGLISH_AU_FEMALE_METRO_EDDIE = "en_au_001"
    ENGLISH_AU_MALE_SMOOTH_ALEX = "en_au_002"
    ENGLISH_UK_MALE_1 = "en_uk_001"
    ENGLISH_UK_MALE_2 = "en_uk_003"
    ENGLISH_US_FEMALE_JESSIE = "en_us_002"
    ENGLISH_US_MALE_JOEY = "en_us_006"
    ENGLISH_US_MALE_PROFESSOR = "en_us_007"
    ENGLISH_US_MALE_SCIENTIST = "en_us_009"
    ENGLISH_US_MALE_CONFIDENCE = "en_us_010"
    FRENCH_MALE_1 = "fr_001"
    FRENCH_MALE_2 = "fr_002"
    GERMAN_FEMALE = "de_001"
    GERMAN_MALE = "de_002"
    ITALIAN_MALE = "it_male_m18"
    SPANISH_MALE = "es_002"
    SPANISH_MALE_JULIO = "es_male_m3"
    SPANISH_FEMALE_ALEJANDRA = "es_female_f6"
    SPANISH_FEMALE_MARIANA = "es_female_fp1"
    SPANISH_ALEX_WARM = "es_mx_002"
    MEXICAN_OPTIMUS_PRIME = "es_mx_male_transformer"
    PORTUGUESE_JULIA = "br_003"
    PORTUGUESE_ANA = "br_004"
    PORTUGUESE_LUCAS = "br_005"
    PORTUGUESE_LHAYS_MACEDO = "pt_female_lhays"
    PORTUGUESE_LAIZZA = "pt_female_laizza"
    PORTUGUESE_OPTIMUS_PRIME = "pt_male_transformer"
    INDONESIAN_FEMALE = "id_001"
    JAPANESE_FEMALE_1 = "jp_001"
    JAPANESE_FEMALE_2 = "jp_003"
    JAPANESE_FEMALE_3 = "jp_005"
    JAPANESE_MALE = "jp_006"
    KOREAN_MALE_1 = "kr_002"
    KOREAN_FEMALE = "kr_003"
    KOREAN_MALE_2 = "kr_004"
    GHOST_FACE = "en_us_ghostface"
    CHEWBACCA = "en_us_chewbacca"
    C3PO = "en_us_c3po"
    STITCH = "en_us_stitch"
    STORMTROOPER = "en_us_stormtrooper"
    ROCKET = "en_us_rocket"
    MADAME_LEOTA = "en_female_madam_leota"
    SONG_CAROLER = "en_male_sing_deep_jingle"
    SONG_CLASSIC_ELECTRIC = "en_male_m03_classical"
    SONG_COTTAGECORE = "en_female_f08_salut_damour"
    SONG_COZY = "en_male_m2_xhxs_m03_christmas"
    SONG_WARMY_BREEZE = "en_female_f08_warmy_breeze"
    SONG_HALLOWEEN = "en_female_ht_f08_halloween"
    SONG_EUPHORIC = "en_female_ht_f08_glorious"
    SONG_HYPETRAIN = "en_male_sing_funny_it_goes_up"
    SONG_TENOR = "en_male_m03_lobby"
    SONG_MELODRAMA = "en_female_ht_f08_wonderful_world"
    SONG_NYE_2023 = "en_female_ht_f08_newyear"
    SONG_THANKSGIVING = "en_male_sing_funny_thanksgiving"
    SONG_SUNSHINE_SOON = "en_male_m03_sunshine_soon"
    SONG_POP_LULLABY = "en_female_f08_twinkle"
    SONG_QUIRKY = "en_male_m2_xhxs_m03_silly"
    STORY_TELLER = "en_male_narration"
    WACKY = "en_male_funny"
    SERIOUS = "en_male_cody"
    EMPATHETIC = "en_female_samc"
    ALFRED = "en_male_jarvis"
    BAE = "en_female_betty"
    BEAUTY_GURU = "en_male_santa_narration"
    SANTA = "en_male_santa"
    SANTA_WO_EFFECT = "en_male_santa_effect"
    BESTIE = "en_female_richgirl"
    CUPID = "en_male_cupid"
    GHOST_HOST = "en_male_ghosthost"
    LORD_CRINGE = "en_male_ukneighbor"
    MAGICIAN = "en_male_wizard"
    MARTY = "en_male_trevor"
    DEBUTANTE = "en_female_shenna"
    AUTHOR = "en_female_makeup"
    PEACEFUL = "en_female_emotional"
    GRANDMA = "en_female_grandma"
    TRICKSTER_GRINCH = "en_male_grinch"
    GOODGUY_DEADPOOL = "en_male_deadpool"
    METICULOUS = "en_male_ukbutler"
    OPTIMUS_PRIME = "en_male_petercullen"
    PIRATE = "en_male_pirate"
    VARSITY = "en_female_pansino"


for voice in Voices:
    assert voice.name == voice.name.upper(), voice.name


__all__ = ["Voices"]
