---
networks:
  pangolin_newt:
    external: true
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    networks:
      - pangolin_newt
    ports:
      - 10000:{{ APPLICATION_PORT }}
    labels:
      - pangolin.public-resources.jellyfin.name=Jellyfin
      - pangolin.public-resources.jellyfin.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.jellyfin.protocol=http
      - pangolin.public-resources.jellyfin.auth.sso-enabled=true
      - pangolin.public-resources.jellyfin.auth.sso-roles[0]=jellyfin
      - pangolin.public-resources.jellyfin.targets[0].method=http
      - pangolin.public-resources.jellyfin.targets[0].port={{ APPLICATION_PORT }}
      - pangolin.public-resources.jellyfin.rules[0].action=allow
      - pangolin.public-resources.jellyfin.rules[0].match=path
      - pangolin.public-resources.jellyfin.rules[0].value=Items/*
      - pangolin.public-resources.jellyfin.rules[1].action=allow
      - pangolin.public-resources.jellyfin.rules[1].match=path
      - pangolin.public-resources.jellyfin.rules[1].value=Videos/*
    volumes:
      - ./config:/config
      - '{{ secrets.JELLYFIN.MEDIA_FOLDER }}:/media'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
