networks:
  "{{ secrets.TRAEFIK_NETWORK }}":
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    networks:
      - '{{ secrets.TRAEFIK_NETWORK }}'
    # ports:
    #   - "8096:{{ APPLICATION_PORT }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ secrets.JELLYFIN.USERNAME }}.entrypoints=web
      - traefik.http.routers.{{ secrets.JELLYFIN.USERNAME }}.rule=Host(`{{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}`)
      - traefik.http.services.{{ secrets.JELLYFIN.USERNAME }}.loadbalancer.server.port={{ APPLICATION_PORT }}
    volumes:
      - ./config:/config
      - "{{ secrets.JELLYFIN.MEDIA_FOLDER }}:/media"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "3"
          memory: 2048M
