---
networks:
  '{{ secrets.TRAEFIK_NETWORK }}':
    external: true
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    networks:
      - '{{ secrets.TRAEFIK_NETWORK }}'
    ports:
      - 10000:{{ APPLICATION_PORT }}
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ USERNAME }}.entrypoints=web
      - traefik.http.routers.{{ USERNAME }}.rule=Host(`{{ SUBDOMAIN
        }}.{{ secrets.MY_DOMAIN }}`)
      - traefik.http.services.{{ USERNAME }}.loadbalancer.server.port={{
        APPLICATION_PORT }}
      - traefik.http.routers.{{ USERNAME }}.service={{ USERNAME }}
      # No need on this server due to wireguard
      # - traefik.http.routers.{{ USERNAME }}.middlewares=authelia@docker
    volumes:
      - ./config:/config
      - '{{ secrets.JELLYFIN.MEDIA_FOLDER }}:/media'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
