# Execute with
# ansible-playbook jellyfin_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Stop, remove image, and start jellyfin service
  hosts: all
  vars:
    USERNAME: '{{ secrets.JELLYFIN.USERNAME }}'
  tasks:
  - name: Stop jellyfin server
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Stop jellyfin container
    community.docker.docker_container:
      name: jellyfin
      state: stopped
      image: lscr.io/linuxserver/jellyfin:latest

  - name: Remove jellyfin container
    community.docker.docker_container:
      name: jellyfin
      state: absent
      image: lscr.io/linuxserver/jellyfin:latest

  - name: Remove jellyfin image
    community.docker.docker_image:
      name: lscr.io/linuxserver/jellyfin
      tag: latest
      state: absent

  - name: Start jellyfin server again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      enabled: true
