version: "3.8"

# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

networks:
  '{{secrets.TRAFIK_NETWORK}}':
    external: true

services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    container_name: reactive_resume_postgres
    hostname: reactive_resume_postgres
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '{{ secrets.REACTIVE_RESUME.POSTGRES_PASSWORD }}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio:latest
    container_name: reactive_resume_minio
    hostname: reactive_resume_minio
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    restart: unless-stopped
    command: server /data
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: '{{ secrets.REACTIVE_RESUME.STORAGE_ACCESS_KEY }}'
      MINIO_ROOT_PASSWORD: '{{ secrets.REACTIVE_RESUME.STORAGE_SECRET_KEY }}'

  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    container_name: reactive_resume_chrome
    hostname: reactive_resume_chrome
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    restart: unless-stopped
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    container_name: reactive_resume_redis
    hostname: reactive_resume_redis
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    restart: unless-stopped
    command: redis-server --requirepass password

  app:
    image: amruthpillai/reactive-resume:latest
    container_name: reactive_resume_app
    hostname: reactive_resume_app
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
      - redis
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: http://{{ secrets.REACTIVE_RESUME.USERNAME }}.{{ secrets.MY_DOMAIN }}
      STORAGE_URL: http://reactive_resume_minio:9000/default

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://reactive_resume_chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:{{ secrets.REACTIVE_RESUME.POSTGRES_PASSWORD }}@reactive_resume_postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: '{{ secrets.REACTIVE_RESUME.ACCESS_TOKEN_SECRET }}'
      REFRESH_TOKEN_SECRET: '{{ secrets.REACTIVE_RESUME.REFRESH_TOKEN_SECRET }}'

      # -- Emails --
      MAIL_FROM: noreply@localhost
      # SMTP_URL: smtp://user:pass@smtp:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: '{{ secrets.REACTIVE_RESUME.STORAGE_ACCESS_KEY }}'
      STORAGE_SECRET_KEY: '{{ secrets.REACTIVE_RESUME.STORAGE_SECRET_KEY }}'
      STORAGE_USE_SSL: false

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@reactive_resume_redis:6379

      # -- Sentry --
      # VITE_SENTRY_DSN: https://id.sentry.io # Optional

      # -- Crowdin (Optional) --
      # CROWDIN_PROJECT_ID:
      # CROWDIN_PERSONAL_TOKEN:

      # -- Email (Optional) --
      # DISABLE_EMAIL_AUTH: true
      # VITE_DISABLE_SIGNUPS: true

      # -- GitHub (Optional) --
      # GITHUB_CLIENT_ID: github_client_id
      # GITHUB_CLIENT_SECRET: github_client_secret
      # GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback

      # -- Google (Optional) --
      # GOOGLE_CLIENT_ID: google_client_id
      # GOOGLE_CLIENT_SECRET: google_client_secret
      # GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ secrets.REACTIVE_RESUME.USERNAME }}.rule=Host(`{{ secrets.REACTIVE_RESUME.USERNAME }}.{{ secrets.MY_DOMAIN }}`)
      - traefik.http.services.{{ secrets.REACTIVE_RESUME.USERNAME }}.loadbalancer.server.port=3000
      - traefik.http.routers.{{ secrets.REACTIVE_RESUME.USERNAME }}.tls=true
      - traefik.http.routers.{{ secrets.REACTIVE_RESUME.USERNAME }}.tls.certresolver=production
      - traefik.http.routers.{{ secrets.REACTIVE_RESUME.USERNAME }}.middlewares=authelia@docker
