# Execute with
# ansible-playbook reactive_resume_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create and start reactive_resume service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.REACTIVE_RESUME.USERNAME }}"
  tasks:
    - name: Stop reactive_resume service
      ansible.builtin.systemd_service:
        name: "{{ USERNAME }}"
        state: stopped
        enabled: false

    - name: Remove reactive_resume_app container
      community.docker.docker_container:
        name: reactive_resume_app
        state: absent
        image: amruthpillai/reactive-resume:latest

    - name: Remove reactive_resume_postgres container
      community.docker.docker_container:
        name: reactive_resume_postgres
        state: absent
        image: postgres:15-alpine

    - name: Remove reactive_resume_minio container
      community.docker.docker_container:
        name: reactive_resume_postgres
        state: absent
        image: minio/minio:latest

    - name: Remove reactive_resume_chrome container
      community.docker.docker_container:
        name: reactive_resume_chrome
        state: absent
        image: browserless/chrome:1.61.0-puppeteer-21.4.1

    - name: Remove reactive_resume_redis container
      community.docker.docker_container:
        name: reactive_resume_redis
        state: absent
        image: redis:alpine

    - name: Remove reactive_resume image
      community.docker.docker_image:
        name: amruthpillai/reactive-resume
        tag: latest
        state: absent

    - name: Start reactive_resume service again
      ansible.builtin.systemd_service:
        name: "{{ USERNAME }}"
        state: started
        daemon_reload: true
        enabled: true
