networks:
  '{{secrets.TRAEFIK_NETWORK}}':
    external: true

services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific
    networks:
    - '{{ secrets.TRAEFIK_NETWORK }}'
    labels:
    - traefik.enable=true
    - traefik.http.routers.{{ SUBDOMAIN }}.entrypoints=web
    - traefik.http.routers.{{ USERNAME }}.rule=Host(`{{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}`)
    - traefik.http.services.{{ USERNAME }}.loadbalancer.server.port={{ APPLICATION_PORT }}