---
networks:
  pangolin_newt:
    external: true
services:
  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    hostname: baikal
    restart: unless-stopped
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.baikal.name=Baikal
      - pangolin.public-resources.baikal.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.baikal.protocol=http
      - pangolin.public-resources.baikal.auth.sso-enabled=false
      - pangolin.public-resources.baikal.targets[0].method=http
      - pangolin.public-resources.baikal.targets[0].hostname=baikal
      - pangolin.public-resources.baikal.targets[0].port={{ APPLICATION_PORT }}
