# Execute with
# ansible-playbook paperless_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Stop, remove image, and start paperless service
  hosts: my_servers
  vars:
    USERNAME: '{{ secrets.PAPERLESS.USERNAME }}'
  tasks:
  - name: Stop paperless service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Stop paperless container
    community.docker.docker_container:
      name: paperless-webserver
      state: stopped
      image: ghcr.io/paperless-ngx/paperless-ngx:latest

  - name: Remove paperless container
    community.docker.docker_container:
      name: paperless-webserver
      state: absent
      image: ghcr.io/paperless-ngx/paperless-ngx:latest

  - name: Stop paperless-broker container
    community.docker.docker_container:
      name: paperless-broker
      state: stopped
      image: docker.io/library/redis:7

  - name: Remove paperless-broker container
    community.docker.docker_container:
      name: paperless-broker
      state: absent
      image: docker.io/library/redis:7

  - name: Remove paperless image
    community.docker.docker_image:
      name: ghcr.io/paperless-ngx/paperless-ngx
      tag: latest
      state: absent

  - name: Start paperless service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      daemon_reload: true
      enabled: true
