<script lang="ts">
    import TournamentGroupStage from "./TournamentGroupStage.svelte"

    let groups = [
        {
            groupId: 1234,
            groupName: 'Group "A"',
            participants: [
                {
                    rank: 1,
                    playerId: 321,
                    name: "MonstR",
                    matches: 3,
                    wins: 3,
                    losses: 0,
                    mapWins: 6,
                    mapLosses: 1,
                    totalScore: "+5",
                },
                {
                    rank: 2,
                    playerId: 322,
                    name: "Iba",
                    matches: 3,
                    wins: 2,
                    losses: 1,
                    mapWins: 4,
                    mapLosses: 2,
                    totalScore: "+2",
                },
                {
                    rank: 3,
                    playerId: 323,
                    name: "Neuling",
                    matches: 3,
                    wins: 1,
                    losses: 2,
                    mapWins: 3,
                    mapLosses: 4,
                    totalScore: "-1",
                },
                {
                    rank: 4,
                    playerId: 324,
                    name: "TerribleOne",
                    matches: 3,
                    wins: 0,
                    losses: 3,
                    mapWins: 0,
                    mapLosses: 6,
                    totalScore: "-6",
                },
            ],
        },
        {
            groupId: 1235,
            groupName: 'Group "B"',
            participants: [
                {
                    rank: 1,
                    playerId: 321,
                    name: "MonstR",
                    matches: 3,
                    wins: 3,
                    losses: 0,
                    mapWins: 6,
                    mapLosses: 1,
                    totalScore: "+5",
                },
                {
                    rank: 2,
                    playerId: 322,
                    name: "Iba",
                    matches: 3,
                    wins: 2,
                    losses: 1,
                    mapWins: 4,
                    mapLosses: 2,
                    totalScore: "+2",
                },
                {
                    rank: 3,
                    playerId: 323,
                    name: "Neuling",
                    matches: 3,
                    wins: 1,
                    losses: 2,
                    mapWins: 3,
                    mapLosses: 4,
                    totalScore: "-1",
                },
                {
                    rank: 4,
                    playerId: 324,
                    name: "TerribleOne",
                    matches: 3,
                    wins: 0,
                    losses: 3,
                    mapWins: 0,
                    mapLosses: 6,
                    totalScore: "-6",
                },
            ],
        },
        {
            groupId: 1236,
            groupName: 'Group "C"',
            participants: [
                {
                    rank: 1,
                    playerId: 321,
                    name: "MonstR",
                    matches: 3,
                    wins: 3,
                    losses: 0,
                    mapWins: 6,
                    mapLosses: 1,
                    totalScore: "+5",
                },
                {
                    rank: 2,
                    playerId: 322,
                    name: "Iba",
                    matches: 3,
                    wins: 2,
                    losses: 1,
                    mapWins: 4,
                    mapLosses: 2,
                    totalScore: "+2",
                },
                {
                    rank: 3,
                    playerId: 323,
                    name: "Neuling",
                    matches: 3,
                    wins: 1,
                    losses: 2,
                    mapWins: 3,
                    mapLosses: 4,
                    totalScore: "-1",
                },
                {
                    rank: 4,
                    playerId: 324,
                    name: "TerribleOne",
                    matches: 3,
                    wins: 0,
                    losses: 3,
                    mapWins: 0,
                    mapLosses: 6,
                    totalScore: "-6",
                },
            ],
        },
        {
            groupId: 1237,
            groupName: 'Group "D"',
            participants: [
                {
                    rank: 1,
                    playerId: 321,
                    name: "MonstR",
                    matches: 3,
                    wins: 3,
                    losses: 0,
                    mapWins: 6,
                    mapLosses: 1,
                    totalScore: "+5",
                },
                {
                    rank: 2,
                    playerId: 322,
                    name: "Iba",
                    matches: 3,
                    wins: 2,
                    losses: 1,
                    mapWins: 4,
                    mapLosses: 2,
                    totalScore: "+2",
                },
                {
                    rank: 3,
                    playerId: 323,
                    name: "Neuling",
                    matches: 3,
                    wins: 1,
                    losses: 2,
                    mapWins: 3,
                    mapLosses: 4,
                    totalScore: "-1",
                },
                {
                    rank: 4,
                    playerId: 324,
                    name: "TerribleOne",
                    matches: 3,
                    wins: 0,
                    losses: 3,
                    mapWins: 0,
                    mapLosses: 6,
                    totalScore: "-6",
                },
            ],
        },
    ]
</script>

<TournamentGroupStage {groups} />
