---
networks:
  pangolin_newt:
    external: true
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest  # TODO pin release: WHY latest tracks rolling
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.stirling.name=Stirling
      - pangolin.public-resources.stirling.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.stirling.protocol=http
      - pangolin.public-resources.stirling.auth.sso-enabled=false
      - pangolin.public-resources.stirling.targets[0].site=local
      - pangolin.public-resources.stirling.targets[0].method=http
      - pangolin.public-resources.stirling.targets[0].hostname=stirling-pdf
      - pangolin.public-resources.stirling.targets[0].port={{ APPLICATION_PORT }}
    volumes:
      - ./trainingData:/usr/share/tessdata  # Required for extra OCR languages
      - ./extraConfigs:/configs
      # - ./customFiles:/customFiles/
      # - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=en_GB
