---
networks:
  '{{secrets.TRAEFIK_NETWORK}}':
    external: true
services:
  mirotalk:
    image: mirotalk/p2p:latest
    container_name: mirotalk
    hostname: mirotalk
    restart: unless-stopped
    volumes:
      - ./.env:/src/.env:ro
    networks:
      - '{{ secrets.TRAEFIK_NETWORK }}'
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ secrets.MIROTALK.USERNAME }}.rule=Host(`{{ secrets.MIROTALK.SUBDOMAIN
        }}.{{ secrets.MY_DOMAIN }}`)
      - traefik.http.services.{{ secrets.MIROTALK.USERNAME }}.loadbalancer.server.port={{
        APPLICATION_PORT }}
      - traefik.http.routers.{{ secrets.MIROTALK.USERNAME }}.tls=true
      - traefik.http.routers.{{ secrets.MIROTALK.USERNAME }}.tls.certresolver=production
      # - traefik.http.routers.{{ secrets.BOOKSTACK.USERNAME }}.middlewares=authelia@docker