---
networks:
  pangolin_newt:
    external: true
services:
  mirotalk:
    image: mirotalk/p2p:latest
    container_name: mirotalk
    hostname: mirotalk
    restart: unless-stopped
    volumes:
      - ./.env:/src/.env:ro
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.mirotalk.name=Mirotalk
      - pangolin.public-resources.mirotalk.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.mirotalk.protocol=http
      - pangolin.public-resources.mirotalk.auth.sso-enabled=false
      - pangolin.public-resources.mirotalk.targets[0].site=local
      - pangolin.public-resources.mirotalk.targets[0].method=http
      - pangolin.public-resources.mirotalk.targets[0].port={{ APPLICATION_PORT }}
