---
api:
  insecure: true
  dashboard: true
providers:
  http:
    endpoint: http://pangolin:3001/api/v1/traefik-config
    pollInterval: 5s
  file:
    filename: /etc/traefik/dynamic_config.yml
experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.3.1
log:
  level: INFO
  format: common
  maxSize: 100
  maxBackups: 3
  maxAge: 3
  compress: true
certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
      email: '{{ secrets.TRAEFIK.MY_EMAIL }}'
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    transport:
      respondingTimeouts:
        readTimeout: 30m
    http:
      tls:
        certResolver: letsencrypt
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedQuestionMark: true
  tcp-5432:
    address: :5432/tcp
serversTransport:
  insecureSkipVerify: true
ping:
  entryPoint: web
