version: '3.5'

networks:
  '{{secrets.TRAFIK_NETWORK}}':
    external: true

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist:latest
    volumes:
    - ./media:/youtube
    - cache:/cache
    environment:
    - ES_URL=http://archivist-es:9200       # needs protocol e.g. http and port
    - REDIS_HOST=archivist-redis            # don't add protocol
    - HOST_UID=1000
    - HOST_GID=1000
    - TA_HOST={{ secrets.TUBEARCHIVIST.USERNAME }}.{{ secrets.MY_DOMAIN }}           # set your host name
    - TA_USERNAME={{ secrets.TUBEARCHIVIST.TA_USERNAME }}             # your initial TA credentials
    - TA_PASSWORD={{ secrets.TUBEARCHIVIST.TA_PASSWORD }}                # your initial TA credentials
    - ELASTIC_PASSWORD={{ secrets.TUBEARCHIVIST.ELASTIC_PASSWORD }}           # set password for Elasticsearch
    - TZ=Europe/Berlin                   # set your time zone
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:8000/health']
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
    - archivist-es
    - archivist-redis
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    labels:
    - traefik.enable=true
    - traefik.http.routers.{{ secrets.TUBEARCHIVIST.USERNAME }}.rule=Host(`{{ secrets.TUBEARCHIVIST.USERNAME }}.{{ secrets.MY_DOMAIN }}`)
    - traefik.http.services.{{ secrets.TUBEARCHIVIST.USERNAME }}.loadbalancer.server.port=8000
    - traefik.http.routers.{{ secrets.TUBEARCHIVIST.USERNAME }}.tls=true
    - traefik.http.routers.{{ secrets.TUBEARCHIVIST.USERNAME }}.tls.certresolver=production
  archivist-redis:
    image: redis/redis-stack-server:latest
    container_name: archivist-redis
    restart: unless-stopped
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    volumes:
    - redis:/data
    depends_on:
    - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es:latest         # only for amd64, or use official es 8.11.0
    container_name: archivist-es
    restart: unless-stopped
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    environment:
    - ELASTIC_PASSWORD={{ secrets.TUBEARCHIVIST.ELASTIC_PASSWORD }}           # matching Elasticsearch password
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    - xpack.security.enabled=true
    - discovery.type=single-node
    - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - es:/usr/share/elasticsearch/data      # check for permission error when using bind mount, see readme

volumes:
  cache:
  redis:
  es:
