# Execute with
# ansible-playbook syncthing_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create and start syncthing service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.SYNCTHING.USERNAME }}"
    SUBDOMAIN: "{{ secrets.SYNCTHING.SUBDOMAIN }}"
    APPLICATION_PORT: "8384"
  tasks:
  - name: Create group
    ansible.builtin.group:
      name: '{{ USERNAME }}'
      state: present

  - name: Create user
    ansible.builtin.user:
      name: '{{ USERNAME }}'
      groups:
      - '{{ USERNAME }}'
      - docker
      shell: '{{ secrets.DEFAULT_SHELL }}'

  - name: Get user id
    ansible.builtin.shell:
      cmd: id {{ USERNAME }} -u
    register: USER_ID

  - name: Get group id
    ansible.builtin.shell:
      cmd: id {{ USERNAME }} -g
    register: GROUP_ID

  - name: Copy docker-compose.yml file
    template:
      src: docker-compose.yml
      dest: /home/{{ USERNAME }}/docker-compose.yml
      
  - name: Tear down existing services
    community.docker.docker_compose_v2:
      project_src: /home/{{ USERNAME }}
      state: absent
      # Comment out to skip update
      remove_images: all

  - name: Run `docker-compose up` again
    community.docker.docker_compose_v2:
      project_src: /home/{{ USERNAME }}
