---
- name: Install packages
  community.general.pacman:
    name:
      - syncthing
      # Terminal
      - fish
      # System & utility tools
      - p7zip  # better zip alternative
      - inxi  # system information
      - btop  # monitor of system resources
      - gdu  # terminal disk usage stats viewer like qdirstat
      # Basic programming and server tools
      - base-devel
      - curl
      - wget
      - cloc
      - jq  # JSON processor
      - openssh
      - cloudflared
      - git
      - lazygit  # git gui for terminal
      - helix
      # Advanced programming tools, languages
      - make  # For AUR packages
      - python-pip
      - python-uv  # python package manager like poetry and pipenv
      - prettier  # formatter for yaml, json, css, markdown
      # Helix language servers
      # Use uv packages for format / lint: pyre, pyright, ruff, djlint for html/jinja
      - ansible-lint
      ## yaml
      - yaml-language-server
      ## html
      - vscode-html-languageserver
      - tailwindcss-language-server  # tailwindcss support in html
      ## toml
      - taplo-cli
    state: present
  become: true
- name: Install bigger packages (>10mb)
  community.general.pacman:
    name:
      - gcc
      - postgresql  # postgres shell, psql
    state: present
  become: true
- name: Start syncthing service for user
  become_user: burny
  ansible.builtin.systemd_service:
    name: syncthing.service
    scope: user
    state: started
    daemon_reload: true
    enabled: true
