---
- name: Main play
  hosts: all
  vars:
    USERNAME: burny
  roles:
    - {role: 01_host_info}
    - {role: 02_basics}
    - {role: 03_packages}
    - {role: 04_aur_packages}
    - {role: 05_flatpak_packages}
