---
networks:
  pangolin_newt:
    external: true
services:
  garage:
    container_name: garage
    hostname: garage
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    networks:
      - pangolin_newt
    labels:
      - pangolin.public-resources.garage-s3.name=Garage S3 API
      - pangolin.public-resources.garage-s3.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.garage-s3.protocol=http
      - pangolin.public-resources.garage-s3.auth.sso-enabled=false
      - pangolin.public-resources.garage-s3.targets[0].site=local
      - pangolin.public-resources.garage-s3.targets[0].method=http
      - pangolin.public-resources.garage-s3.targets[0].port=3900
      - pangolin.public-resources.garage-admin.name=Garage Admin Console
      - pangolin.public-resources.garage-admin.full-domain={{ ADMINSUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.garage-admin.protocol=http
      - pangolin.public-resources.garage-admin.auth.sso-enabled=true
      - pangolin.public-resources.garage-admin.targets[0].site=local
      - pangolin.public-resources.garage-admin.targets[0].method=http
      - pangolin.public-resources.garage-admin.targets[0].port=3903
    volumes:
      - ./garage_data:/var/lib/garage/data
      - ./garage_meta:/var/lib/garage/meta
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      - GARAGE_ADMIN_TOKEN={{ secrets.GARAGE.GARAGE_ADMIN_TOKEN }}
