# Execute with
# ansible-playbook changedetection_update.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Stop, remove image, and start changedetection service
  hosts: my_servers
  vars:
    USERNAME: '{{ secrets.CHANGE_DETECTION.USERNAME }}'
  tasks:
  - name: Stop changedetection service
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: stopped
      enabled: false

  - name: Remove changedetection container
    community.docker.docker_container:
      name: changedetection
      state: absent
      image: ghcr.io/dgtlmoon/changedetection.io

  - name: Remove changedetection container
    community.docker.docker_container:
      name: changedetection-playwright-chrome
      state: absent
      image: browserless/chrome:1.60-chrome-stable

  - name: Remove changedetection image
    community.docker.docker_image:
      name: ghcr.io/dgtlmoon/changedetection.io
      tag: latest
      state: absent

  - name: Start changedetection service again
    ansible.builtin.systemd_service:
      name: '{{ USERNAME }}'
      state: started
      daemon_reload: true
      enabled: true
