VERSION 0.6
# earthly +all --PYTHONVERSION=3.13
ARG PYTHONVERSION=3.13
FROM ghcr.io/astral-sh/uv:python${PYTHONVERSION}-bookworm-slim
WORKDIR /root/burny_common

install-dev:
    COPY uv.lock pyproject.toml ./
    RUN uv sync --frozen --no-cache --no-install-project
    COPY burny_common burny_common

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install uv
    # uv sync

    # Convert single to double quotes
    RUN uv run ruff check . --select Q --fix
    # Remove unused imports
    RUN uv run ruff check . --select F --fix
    # Sort imports
    RUN uv run ruff check . --select I --fix
    # Format code
    RUN uv run ruff format .

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN uv run ruff format . --check --diff

# Ignore errors via "# noqa: F841"
lint:
    FROM +install-dev
    RUN uv run ruff check .

# Try to build project
build:
    FROM +install-dev
    RUN uv build

# Ignore errors via "# pyre-fixme[11]"
pyrefly:
    FROM +install-dev
    RUN uv run pyrefly check

# TODO Add tests
# pytest:
#     FROM +install-dev
#     RUN uv run pytest

pre-commit:
    BUILD +format-check
    BUILD +lint
    BUILD +pyrefly
    BUILD +build

all:
    BUILD +pre-commit
    #BUILD +pytest
