import type { BookWithChapters } from "$lib/types/audiobook"

export const mock_book_data: BookWithChapters = {
    book: {
        id: 1,
        uploaded_by: "admin",
        book_title: "The Great Gatsby",
        book_author: "F. Scott Fitzgerald",
        custom_book_title: "",
        custom_book_author: "",
        chapter_count: 9,
        upload_date: "2024-01-15T10:30:00Z",
    },
    chapters: [
        {
            id: 1,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: true,
            chapter_title: "Chapter 1 - In My Younger Years",
            chapter_number: 1,
            sentence_count: 142,
            minio_object_name: "book_1_chapter_1.mp3",
            minio_presigned_url: "https://example.com/audio/chapter1.mp3",
        },
        {
            id: 2,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: true,
            chapter_title: "Chapter 2 - The Party",
            chapter_number: 2,
            sentence_count: 189,
            minio_object_name: "book_1_chapter_2.mp3",
            minio_presigned_url: "https://example.com/audio/chapter2.mp3",
        },
        {
            id: 3,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: false,
            chapter_title: "Chapter 3 - Gatsby's Mansion",
            chapter_number: 3,
            sentence_count: 215,
            minio_object_name: null,
            minio_presigned_url: "",
        },
        {
            id: 4,
            book_id: 1,
            number_in_queue: 1,
            is_converting: false,
            has_audio: false,
            chapter_title: "Chapter 4 - The Affair",
            chapter_number: 4,
            sentence_count: 178,
            minio_object_name: null,
            minio_presigned_url: "",
        },
        {
            id: 5,
            book_id: 1,
            number_in_queue: null,
            is_converting: true,
            has_audio: false,
            chapter_title: "Chapter 5 - Confrontation",
            chapter_number: 5,
            sentence_count: 156,
            minio_object_name: null,
            minio_presigned_url: "",
        },
        {
            id: 6,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: false,
            chapter_title: "Chapter 6 - Aftermath",
            chapter_number: 6,
            sentence_count: 203,
            minio_object_name: null,
            minio_presigned_url: "",
        },
        {
            id: 7,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: true,
            chapter_title: "Chapter 7 - The Climax",
            chapter_number: 7,
            sentence_count: 234,
            minio_object_name: "book_1_chapter_7.mp3",
            minio_presigned_url: "https://example.com/audio/chapter7.mp3",
        },
        {
            id: 8,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: false,
            chapter_title: "Chapter 8 - Resolution",
            chapter_number: 8,
            sentence_count: 167,
            minio_object_name: null,
            minio_presigned_url: "",
        },
        {
            id: 9,
            book_id: 1,
            number_in_queue: null,
            is_converting: false,
            has_audio: false,
            chapter_title: "Chapter 9 - Epilogue",
            chapter_number: 9,
            sentence_count: 98,
            minio_object_name: null,
            minio_presigned_url: "",
        },
    ],
    available_voices: ["en-US-AriaNeural", "en-GB-RyanNeural", "en-US-GuyNeural"],
}
