---
# Execute with
# ansible-playbook db_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: server_group4
  vars:
    USERNAME: '{{ secrets.DATABASES_DEV.USERNAME }}'
  tasks:
    - include_tasks: ../setup_cloudflare_a_record.yml
      loop:
        - hostname: '{{ secrets.DATABASES_DEV.POSTGRES_DEV_SUBDOMAIN }}.{{ secrets.MY_DOMAIN
            }}'
        - hostname: '{{ secrets.DATABASES_DEV.POSTGRES_TEST_SUBDOMAIN }}.{{ secrets.MY_DOMAIN
            }}'
        - hostname: '{{ secrets.DATABASES_DEV.MARIA_DEV_SUBDOMAIN }}.{{ secrets.MY_DOMAIN
            }}'
        - hostname: '{{ secrets.DATABASES_DEV.MARIA_TEST_SUBDOMAIN }}.{{ secrets.MY_DOMAIN
            }}'
      loop_control:
        loop_var: item
      when: "'remote_servers' in group_names"
    - name: Create group
      ansible.builtin.group:
        name: '{{ USERNAME }}'
        state: present
    - name: Create user
      ansible.builtin.user:
        name: '{{ USERNAME }}'
        groups:
          - '{{ USERNAME }}'
          - docker
        shell: '{{ secrets.DEFAULT_SHELL }}'
    - name: Copy docker-compose.yml file
      template:
        src: docker-compose.yml
        dest: /home/{{ USERNAME }}/docker-compose.yml
    - name: Run `docker-compose up` again
      community.docker.docker_compose_v2:
        project_src: /home/{{ USERNAME }}
        pull: always
