name: Test Discord Bot

on:
  push:
    paths:
      - discord_bot/**
      - .github/workflows/discord_bot.yml
  pull_request:
    branches: [master, develop]

env:
  SUBDIRECTORY: discord_bot

jobs:
  run_pre_commit_checks:
    name: pre_commit_check_py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run pre-commit hooks
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run pre-commit run --all-files --hook-stage push

  test_backend:
    name: test_backend_py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

        # https://earthly.dev/get-earthly
      - name: Install Earthly
        run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

      - name: Install
        working-directory: ${{ env.SUBDIRECTORY }}
        run: |
          earthly +install-dev --verbose true --PYTHONVERSION=${{ matrix.python-version }}

      - name: Run code checks and tests
        working-directory: ${{ env.SUBDIRECTORY }}
        run: earthly +all --verbose true --PYTHONVERSION=${{ matrix.python-version }}

  #    - name: Save cache
  #      working-directory: ${{ env.SUBDIRECTORY }}
  #      run: earthly +export-cache --verbose true --PYTHONVERSION=${{ matrix.python-version }}
