name: run_earthly_checks


on: [push, pull_request]

jobs:
  run_earthly_checks_backend:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache .venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: |
        sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

    - name: Run code checks and tests
      run: |
        earthly +install-backend --verbose true --PYTHONVERSION==${{ matrix.python-version }}
        earthly +check-backend --verbose true --PYTHONVERSION==${{ matrix.python-version }}
        earthly +export-cache --verbose true --PYTHONVERSION=${{ matrix.python-version }}

  run_earthly_checks_frontend:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18', '19']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: |
        sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

    - name: Run code checks and tests
      run: |
        earthly +install-frontend --verbose true --NODEVERSION==${{ matrix.node }}
        earthly +check-frontend --verbose true --NODEVERSION==${{ matrix.node }}
