name: run_earthly_checks

on: [push, pull_request]

jobs:
  run_earthly_checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # https://earthly.dev/get-earthly
      - name: Install Earthly
        run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

      - name: Install
        run: |
          touch discord_bot/SECRETS.toml
          earthly +install-all --verbose true --PYTHONVERSION=${{ matrix.python-version }}

      - name: Run code checks and tests
        run: earthly +all --verbose true --PYTHONVERSION=${{ matrix.python-version }}
#    - name: Save cache
#      run: earthly +export-cache-backend --verbose true --PYTHONVERSION=${{ matrix.python-version }}
