name: Test Fastapi Server

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - fastapi_server/**
      - .github/workflows/fastapi_server.yml
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

env:
  SUBDIRECTORY: fastapi_server

jobs:
  run_lint_checks:
    name: lint_check_py${{ matrix.python-version }}
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.13", "3.14"]
        include:
          - os: ubuntu-latest
            python-version: "3.15"
            experimental: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run lint
        working-directory: ${{ env.SUBDIRECTORY }}
        env:
          LINT_STRICT: 1
        run: bash lint.sh

  test_backend:
    name: test_backend_py${{ matrix.python-version }}
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu-latest
            python-version: "3.15"
            experimental: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Set up postgres and minio test instances
        working-directory: ${{ env.SUBDIRECTORY }}
        run: docker compose --profile test up -d

      - name: Install espeak-ng and ffmpeg
        run: sudo apt-get update && sudo apt-get install -y espeak-ng ffmpeg

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run pytest
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run pytest test --random-order
