name: Test Fastapi Server

on:
  push:
    paths:
      - fastapi_server/**
      - .github/workflows/fastapi_server.yml
  pull_request:
    branches: [master, develop]

env:
  SUBDIRECTORY: fastapi_server

jobs:
  run_pre_commit_checks:
    name: pre_commit_check_py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run pre-commit hooks
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run pre-commit run --all-files --hook-stage push

  test_backend:
    name: test_backend_py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Set up postgres and minio test instances
        working-directory: ${{ env.SUBDIRECTORY }}
        run: docker compose --profile test up -d

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install packages
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run pytest
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run pytest test --random-order
