name: publish_burny_common


on:
  push:
    paths:
    - burny_common/**
    - .github/workflows/publish_burny_common.yml
  pull_request:
    branches:
    - master
    - develop

env:
  SUBDIRECTORY: burny_common

jobs:
  run_code_check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: |
        sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

    - name: Run code checks and tests
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        earthly +all --verbose true

  build_and_publish:
    needs: [run_code_check]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Make poetry use local .venv folder
      run: poetry config virtualenvs.in-project true

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: ${{ env.SUBDIRECTORY }}/.venv
        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ env.SUBDIRECTORY }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        pip install poetry
        poetry install --no-dev

    - name: Build
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        poetry build

      # Publish package on pypi
    - name: Publish
      working-directory: ${{ env.SUBDIRECTORY }}
      continue-on-error: true
      run: |
        poetry publish --username ${{ secrets.pypi_username }} --password ${{ secrets.pypi_password }}
