name: publish_example_package


on:
  push:
    paths:
    - example_package/**
    - .github/workflows/publish_example_package.yml
  pull_request:
    branches:
    - master
    - develop

jobs:
  build_and_publish:
    env:
      SUBDIRECTORY: example_package
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Make poetry use local .venv folder
      run: poetry config virtualenvs.in-project true

    - name: Cache poetry
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ matrix.os }}-${{ matrix.python-version }}-poetry-${{ env.SUBDIRECTORY }}-${{ hashFiles('poetry.lock') }}

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ matrix.os }}-${{ matrix.python-version }}-poetry-${{ env.SUBDIRECTORY }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        pip install poetry
        cd ${{ env.SUBDIRECTORY }}
        poetry install --no-dev

    - name: Build
      run: |
        cd ${{ env.SUBDIRECTORY }}
        poetry build

      # Publish package on pypi
    - name: Publish
      continue-on-error: true
      run: |
        cd ${{ env.SUBDIRECTORY }}
        poetry publish --username ${{ secrets.pypi_username }} --password ${{ secrets.pypi_password }}
