name: Run Python Examples

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - python_examples/**
      - .github/workflows/python_examples.yml
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

env:
  SUBDIRECTORY: python_examples

jobs:
  run_lint_checks:
    name: lint_check_py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run lint
        working-directory: ${{ env.SUBDIRECTORY }}
        env:
          LINT_STRICT: 1
        run: bash lint.sh

  run_code_check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Start MongoDB
        uses: ankane/setup-mongodb@v1

      - name: Start Postgres
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: 14

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install packages
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync --frozen --no-cache --no-install-project

      - name: Run pytest
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run pytest

  run_python_examples:
    needs: [run_code_check]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
        include:
          - os: macos-latest
            python-version: "3.13"
          # Doesn't work on windows
          # - os: windows-latest
          #   python-version: "3.11"

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Start MongoDB
        uses: ankane/setup-mongodb@v1
      #      with:
      #        mongodb-version: 5.0

      - name: Start Postgres
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: 14

      - name: Print environment variables (linux)
        run: |
          printenv

      - name: Install Python dependencies
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv sync

      - name: Run Python tests
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run python -m pytest

      - name: Run main.py
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run python src/main.py

      - name: Run database readme example - peewee
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run python src/examples/databases/readme_peewee_example.py

      - name: Run database readme example - sqlalchemy
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run python src/examples/databases/readme_sqlalchemy_example.py

      - name: Run database readme example - sqlite
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run python src/examples/databases/readme_sqlite_example.py

      - name: Run database readme example - tinydb
        working-directory: ${{ env.SUBDIRECTORY }}
        run: uv run python src/examples/databases/readme_tinydb_example.py
