name: test_bored_gems


on:
  push:
    paths:
    - bored_gems/**
    - .github/workflows/test_bored_gems.yml
  pull_request:
    branches:
    - master
    - develop

env:
  SUBDIRECTORY: bored_gems

jobs:
  test_bored_gems:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18', '19']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: |
        sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

#    - name: Cache npm
#      uses: actions/cache@v3
#      with:
#        path: ~/.npm
#        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Run code checks and tests
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        earthly +install-all --verbose true --NODEVERSION=${{ matrix.node }}
        earthly +all --verbose true --NODEVERSION=${{ matrix.node }}
