name: test_svelte_frontend


on:
  push:
    paths:
    - burny_common/**
    - fastapi_server/**
    - poetry.lock
    - svelte_frontend/**
    - .github/workflows/test_svelte_frontend.yml
  pull_request:
    branches:
    - master
    - develop

env:
  SUBDIRECTORY: svelte_frontend
  BACKEND_SUBDIRECTORY: fastapi_server

jobs:
  test_svelte_frontend:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18', '19']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

    - name: Install
      working-directory: ${{ env.SUBDIRECTORY }}
      run: earthly +install-all --verbose true --NODEVERSION=${{ matrix.node }}

    - name: Run code checks and tests
      working-directory: ${{ env.SUBDIRECTORY }}
      run: earthly +all --verbose true --NODEVERSION=${{ matrix.node }}

# TODO Fix integration test
#  test_integration:
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest]
#        python-version: ['3.10']
#        node: ['14', '16', '18']
#    runs-on: ${{ matrix.os }}
#
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Python ${{ matrix.python-version }}
#      id: setup-python
#      uses: actions/setup-python@v4
#      with:
#        python-version: ${{ matrix.python-version }}
#
#    - name: Install Poetry
#      run: pip install poetry
#
#    - name: Make poetry use local .venv folder
#      run: poetry config virtualenvs.in-project true
#
#    - name: Set up cache (backend)
#      uses: actions/cache@v3
#      with:
#        path: ${{ env.BACKEND_SUBDIRECTORY }}/.venv
#        key: ${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-poetry-${{ env.BACKEND_SUBDIRECTORY }}-${{ hashFiles('poetry.lock') }}
#
#    - name: Install Python dependencies
#      working-directory: ${{ env.BACKEND_SUBDIRECTORY }}
#      run: poetry install
#
#    - name: Install playwright browsers
#      working-directory: ${{ env.BACKEND_SUBDIRECTORY }}
#      run: poetry run playwright install
#
#    - name: Set up Node ${{ matrix.node }}
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node }}
#
#    - name: Cache npm
#      uses: actions/cache@v3
#      with:
#        path: ~/.npm
#        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}
#
#    - name: Install npm dependencies
#      working-directory: ${{ env.SUBDIRECTORY }}
#      run: npm install
#
#    - name: Run integration tests
#      if: ${{ matrix.node != '14' }}
#      working-directory: ${{ env.BACKEND_SUBDIRECTORY }}
#      run: poetry run pytest test_integration/test_integration.py
