name: test_svelte_frontend


on:
  push:
    paths:
    - burny_common/**
    - fastapi_server/**
    - poetry.lock
    - svelte_frontend/**
    - .github/workflows/test_svelte_frontend.yml
  pull_request:
    branches:
    - master
    - develop

env:
  SUBDIRECTORY: svelte_frontend
  BACKEND_SUBDIRECTORY: fastapi_server

jobs:
  test_svelte_frontend:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18', '19']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

    - name: Install
      working-directory: ${{ env.SUBDIRECTORY }}
      run: earthly +install-all --verbose true --NODEVERSION=${{ matrix.node }}

    - name: Run code checks and tests
      working-directory: ${{ env.SUBDIRECTORY }}
      run: earthly +all --verbose true --NODEVERSION=${{ matrix.node }}

  test_integration:
    needs: [test_svelte_frontend]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
        node: ['18', '19']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # https://earthly.dev/get-earthly
    - name: Install Earthly
      run: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'

    - name: Install
      working-directory: ${{ env.BACKEND_SUBDIRECTORY }}
      run: earthly +install-integration --verbose true --PYTHONVERSION=${{ matrix.python-version }} --NODEVERSION=${{ matrix.node }}

    - name: Run integration-tests
      working-directory: ${{ env.BACKEND_SUBDIRECTORY }}
      run: earthly +integration-test --verbose true --PYTHONVERSION=${{ matrix.python-version }} --NODEVERSION=${{ matrix.node }}
