name: test_supabase_stream_scripts


on:
  push:
    paths:
    - supabase_stream_scripts/**
    - .github/workflows/test_supabase_stream_scripts.yml
  pull_request:
    branches:
    - master
    - develop

env:
  SUBDIRECTORY: supabase_stream_scripts

jobs:
  test_supabase_stream_scripts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16', '18']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        npm install

    - name: Run build command
      if: ${{ matrix.node != '12' }}
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        npm run build

    - name: Run tests
      working-directory: ${{ env.SUBDIRECTORY }}
      run: |
        rm tsconfig.json
        npm run test
