name: test_svelte_frontend


on:
  push:
    paths:
    - supabase_stream_scripts/**
    - .github/workflows/test_supabase_stream_scripts.yml
  pull_request:
    branches:
    - master
    - develop

jobs:
  test_frontend:
    env:
      SUBDIRECTORY: supabase_stream_scripts
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Run tests
      run: |
        npm run test
