name: test_svelte_frontend


on:
  push:
    paths:
    - burny_common/**
    - fastapi_server/**
    - poetry.lock
    - svelte_frontend/**
    - .github/workflows/test_svelte_frontend.yml
  pull_request:
    branches:
    - master
    - develop

jobs:
  test_svelte_frontend:
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['14', '16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Run build command
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm run build

    - name: Install playwright browsers
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npx playwright install
      if: ${{ matrix.node != '14' }}

    - name: Run tests
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm run test
      if: ${{ matrix.node != '14' }}


  test_e2e:
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        node: ['16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Make poetry use local .venv folder
      run: poetry config virtualenvs.in-project true

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ matrix.os }}-$(python --version)-poetry-${{ env.SUBDIRECTORY }}-${{ hashFiles('poetry.lock') }}

    - name: Install Python dependencies
      run: |
        poetry install

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Install playwright browsers
      run: |
        cd ${{ env.SUBDIRECTORY }}
        poetry run playwright install

    - name: Run e2e tests
      run: |
        poetry run pytest ${{ env.SUBDIRECTORY }}/test_frontend/test_e2e.py


  test_integration:
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
        node: ['16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install poetry

    - name: Make poetry use local .venv folder
      run: poetry config virtualenvs.in-project true

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ matrix.os }}-$(python --version)-poetry-${{ env.SUBDIRECTORY }}-${{ hashFiles('poetry.lock') }}

    - name: Install Python dependencies
      run: |
        poetry install

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Install playwright browsers
      run: |
        cd ${{ env.SUBDIRECTORY }}
        poetry run playwright install

    - name: Run integration tests
      run: |
        poetry run pytest ${{ env.SUBDIRECTORY }}/test_frontend/test_integration.py
