name: test_replay_comparer


on:
  push:
    paths:
    - burny_common/**
    - fastapi_server/**
    - poetry.lock
    - replay_comparer/**
    - .github/workflows/test_replay_comparer.yml
  pull_request:
    branches:
    - master
    - develop

jobs:
  test_replay_comparer:
    env:
      SUBDIRECTORY: replay_comparer
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install --production

    - name: Run build command
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm run build
      if: ${{ matrix.node != '12' }}

      # - name: Run tests
      #   run: |
      #       npm run test
