name: test_svelte_frontend


on:
  push:
    paths:
    - burny_common/**
    - fastapi_server/**
    - poetry.lock
    - svelte_frontend/**
    - .github/workflows/test_svelte_frontend.yml
  pull_request:
    branches:
    - master
    - develop

jobs:
  test_frontend:
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

      # - name: Run tests
      #   run: |
      #       npm run test

  test_e2e:
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        node: ['16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install Python dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Run e2e tests
      run: |
        poetry run pytest ${{ env.SUBDIRECTORY }}/test_frontend/test_e2e.py


  test_integration:
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
        node: ['16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install Python dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Run integration tests
      run: |
        poetry run pytest ${{ env.SUBDIRECTORY }}/test_frontend/test_integration.py

  deploy_frontend:
    if: github.ref == 'refs/heads/master'
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16']
    runs-on: ${{ matrix.os }}
    needs: [test_frontend, test_e2e, test_integration]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-production-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install --production

    - name: Build frontend
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npx cross-env BASE_URL='/monorepo' svelte-kit build

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        committer: Deployer Bot <deploy@foo.bar>
        author: Deployer Bot <deploy@foo.bar>
        allow_empty_commit: false
        target_branch: gh-pages
        build_dir: ${{ env.SUBDIRECTORY }}/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_frontend_dev:
    if: github.ref == 'refs/heads/develop'
    env:
      SUBDIRECTORY: svelte_frontend
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-dev-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install --production

    - name: Build frontend
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npx cross-env BASE_URL='/monorepodev' svelte-kit build

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        repo: burnysc2/monorepodev
        committer: Deployer Bot <deploy@foo.bar>
        author: Deployer Bot <deploy@foo.bar>
        allow_empty_commit: false
        target_branch: gh-pages
        build_dir: ${{ env.SUBDIRECTORY }}/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.PAT_MONOREPODEV_DEPLOY }}

