name: test_bored_gems


on:
  push:
    paths:
    - bored_gems/**
    - .github/workflows/test_bored_gems.yml
  pull_request:
    branches:
    - master
    - develop

jobs:
  test_supabase_stream_scripts:
    env:
      SUBDIRECTORY: bored_gems
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['16', '18']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm install

    - name: Run build command
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm run build

    - name: Install playwright browsers
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npx playwright install
      if: ${{ matrix.node != '14' }}

    - name: Run tests
      run: |
        cd ${{ env.SUBDIRECTORY }}
        npm run test
      if: ${{ matrix.node != '14' }}
