name: test_replay_comparer


on:
  push:
    paths:
    - burny_common/**
    - fastapi_server/**
    - poetry.lock
    - replay_comparer/**
    - .github/workflows/test_replay_comparer.yml
  pull_request:
    branches:
    - master
    - develop

env:
  SUBDIRECTORY: replay_comparer

jobs:
  test_replay_comparer:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16', '18']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.SUBDIRECTORY }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      working-directory: ${{ env.SUBDIRECTORY }}
      run: npm install --production

    - name: Run build command
      if: ${{ matrix.node != '12' }}
      working-directory: ${{ env.SUBDIRECTORY }}
      run: npm run build

      # - name: Run tests
      #   run: |
      #       npm run test
