name: Test Transcriber Backend

on:
  push:
    paths:
      - transcribe_website/transcriber_backend/**
      - .github/workflows/transcriber_backend.yml
  pull_request:
    branches: [master, develop]

jobs:
  install-packages:
    name: uv sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
      - name: Run uv sync
        run: uv sync
        working-directory: transcribe_website/transcriber_backend
