---
# https://hub.docker.com/_/nextcloud/
# https://hub.docker.com/_/postgres/
networks:
  pangolin_newt:
    external: true
  nextcloud_internal:
    internal: true
services:
  db:
    # https://hub.docker.com/_/postgres/tags
    image: postgres:18-alpine
    container_name: nextcloud_db
    hostname: nextcloud_db
    networks:
      - nextcloud_internal
    restart: unless-stopped
    environment:
      # PostgreSQL configuration
      - POSTGRES_USER={{ secrets.NEXTCLOUD.DB_USERNAME }}
      - POSTGRES_PASSWORD={{ secrets.NEXTCLOUD.DB_PASSWORD }}
      - POSTGRES_DB={{ secrets.NEXTCLOUD.DB_NAME }}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{ secrets.NEXTCLOUD.DB_USERNAME }} -d {{ secrets.NEXTCLOUD.DB_NAME }}"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql
  nextcloud:
    # https://hub.docker.com/_/nextcloud/tags
    image: nextcloud:stable
    container_name: nextcloud_server
    hostname: nextcloud_server
    networks:
      - pangolin_newt
      - nextcloud_internal
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    labels:
      - pangolin.public-resources.cloud.name=Nextcloud
      - pangolin.public-resources.cloud.full-domain={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      - pangolin.public-resources.cloud.protocol=http
      - pangolin.public-resources.cloud.auth.sso-enabled=false
      - pangolin.public-resources.cloud.targets[0].site=local
      - pangolin.public-resources.cloud.targets[0].method=http
      - pangolin.public-resources.cloud.targets[0].hostname=nextcloud_server
      - pangolin.public-resources.cloud.targets[0].port={{ APPLICATION_PORT }}
    environment:
      # Trusted domains for Nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS={{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}
      
      # Bind the Apache server to the configured port inside the container
      - APACHE_PORT={{ APPLICATION_PORT }}
      
      # Bootstrap administrative credentials
      - NEXTCLOUD_ADMIN_USER={{ secrets.NEXTCLOUD.ADMIN_USERNAME }}
      - NEXTCLOUD_ADMIN_PASSWORD={{ secrets.NEXTCLOUD.ADMIN_PASSWORD }}
      
      # PostgreSQL database connection
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_USER={{ secrets.NEXTCLOUD.DB_USERNAME }}
      - POSTGRES_PASSWORD={{ secrets.NEXTCLOUD.DB_PASSWORD }}
      - POSTGRES_DB={{ secrets.NEXTCLOUD.DB_NAME }}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:{{ APPLICATION_PORT }}/status.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/var/www/html
volumes:
  db_data: null
