---
networks:
  '{{ secrets.TRAEFIK_NETWORK }}':
    external: true
services:
  wireguard:
    # Wireguard host on first run will create keys in './wireguard/peerX/peerX.conf'
    # Copy .conf files to clients under './wireguard/wg_confs/wg0.conf'
    # Change last line to (remove ip6)
    # AllowedIPs = 10.0.0.0/24
    # Add following line to re-establish connection every 25s
    # PersistentKeepalive = 25
    # Verify by pinging clients:
    # docker exec -it wireguard ping 10.0.0.1 to 10.0.0.3
    # docker exec -it wireguard nc -u -z MY_IP MY_PORT
    container_name: wireguard
    restart: unless-stopped
    image: linuxserver/wireguard:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./wireguard:/config
  traefik:
    # Traefik on wireguard client
    image: traefik:3.3.4
    container_name: traefik
    # hostname: traefik
    restart: unless-stopped
    network_mode: host
    # network_mode: service:wireguard
    volumes:
      # Store ssl entries in acme.json
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`{{ TRAEFIK_URL }}`)
      - traefik.http.routers.api.entryPoints=web
      - traefik.http.routers.api.service=api@internal
      - traefik.http.services.api.loadbalancer.server.port={{ APPLICATION_PORT }}
