# Execute with
# ansible-playbook traefik_setup.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: my_servers
  vars:
    USERNAME: "{{ secrets.TRAEFIK.USERNAME }}"
    SUBDOMAIN: "{{ secrets.TRAEFIK.USERNAME }}"
    APPLICATION_PORT: "8080"
  tasks:
  - name: Create group
    ansible.builtin.group:
      name: '{{ USERNAME }}'
      state: present

  - name: Create user
    ansible.builtin.user:
      name: '{{ USERNAME }}'
      groups:
      - '{{ USERNAME }}'
      - docker
      shell: '{{ secrets.DEFAULT_SHELL }}'

  # https://hollo.me/devops/routing-to-multiple-docker-compose-development-setups-with-traefik.html
  - name: Create docker external network
    docker_network:
      name: '{{ secrets.TRAFIK_NETWORK }}'
      internal: false
      attachable: true
      driver: bridge

  - name: Copy docker-compose.yml file
    template:
      src: docker-compose.yml
      dest: /home/{{ USERNAME }}/docker-compose.yml

  - name: Create directories
    file:
      path: /home/{{ USERNAME }}/traefik
      recurse: true
      state: directory

  - name: Copy traefik.yml file
    template:
      src: traefik.yml
      dest: /home/{{ USERNAME }}/traefik/traefik.yml

  - name: Tear down existing services
    community.docker.docker_compose_v2:
      project_src: /home/{{ USERNAME }}
      state: absent
      # Comment out to skip update
      # remove_images: all

  - name: Run `docker-compose up` again
    community.docker.docker_compose_v2:
      project_src: /home/{{ USERNAME }}
