# Static configuration
log:
  # level: DEBUG
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  pgsql:
    address: ":5432"
  mariadb:
    address: ":3306"

certificatesResolvers:
  production:
    acme:
      email: "{{ secrets.TRAEFIK.MY_EMAIL }}"
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {}

providers:
  docker:
    exposedbydefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "{{ secrets.TRAEFIK_NETWORK }}"
  file:
    filename: "/etc/traefik/dynamic.yml"

api:
  dashboard: true
  insecure: false